<?php

/**
 * BaseCommission_intervenant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $commission_id
 * @property integer $intervenant_id
 * @property Commission $Commission
 * @property Intervenant $Intervenant
 * 
 * @method integer                getCommissionId()   Returns the current record's "commission_id" value
 * @method integer                getIntervenantId()  Returns the current record's "intervenant_id" value
 * @method Commission             getCommission()     Returns the current record's "Commission" value
 * @method Intervenant            getIntervenant()    Returns the current record's "Intervenant" value
 * @method Commission_intervenant setCommissionId()   Sets the current record's "commission_id" value
 * @method Commission_intervenant setIntervenantId()  Sets the current record's "intervenant_id" value
 * @method Commission_intervenant setCommission()     Sets the current record's "Commission" value
 * @method Commission_intervenant setIntervenant()    Sets the current record's "Intervenant" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCommission_intervenant extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('commission_intervenant');
        $this->hasColumn('commission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('intervenant_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commission', array(
             'local' => 'commission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Intervenant', array(
             'local' => 'intervenant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}