<?php

/**
 * BaseValorisation_externe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $statut_valorisation_externe_id
 * @property integer $contrat_id
 * @property integer $organisme_id
 * @property integer $valorisation_bpi_id
 * @property Statut_valorisation_externe $Statut_valorisation_externe
 * @property Contrat $Contrat
 * @property Organisme $Organisme
 * @property Valorisation_bpi $Valorisation_bpi
 * 
 * @method integer                     getId()                             Returns the current record's "id" value
 * @method integer                     getStatutValorisationExterneId()    Returns the current record's "statut_valorisation_externe_id" value
 * @method integer                     getContratId()                      Returns the current record's "contrat_id" value
 * @method integer                     getOrganismeId()                    Returns the current record's "organisme_id" value
 * @method integer                     getValorisationBpiId()              Returns the current record's "valorisation_bpi_id" value
 * @method Statut_valorisation_externe getStatutValorisationExterne()      Returns the current record's "Statut_valorisation_externe" value
 * @method Contrat                     getContrat()                        Returns the current record's "Contrat" value
 * @method Organisme                   getOrganisme()                      Returns the current record's "Organisme" value
 * @method Valorisation_bpi            getValorisationBpi()                Returns the current record's "Valorisation_bpi" value
 * @method Valorisation_externe        setId()                             Sets the current record's "id" value
 * @method Valorisation_externe        setStatutValorisationExterneId()    Sets the current record's "statut_valorisation_externe_id" value
 * @method Valorisation_externe        setContratId()                      Sets the current record's "contrat_id" value
 * @method Valorisation_externe        setOrganismeId()                    Sets the current record's "organisme_id" value
 * @method Valorisation_externe        setValorisationBpiId()              Sets the current record's "valorisation_bpi_id" value
 * @method Valorisation_externe        setStatutValorisationExterne()      Sets the current record's "Statut_valorisation_externe" value
 * @method Valorisation_externe        setContrat()                        Sets the current record's "Contrat" value
 * @method Valorisation_externe        setOrganisme()                      Sets the current record's "Organisme" value
 * @method Valorisation_externe        setValorisationBpi()                Sets the current record's "Valorisation_bpi" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseValorisation_externe extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('valorisation_externe');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('statut_valorisation_externe_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contrat_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valorisation_bpi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Statut_valorisation_externe', array(
             'local' => 'statut_valorisation_externe_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Contrat', array(
             'local' => 'contrat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Valorisation_bpi', array(
             'local' => 'valorisation_bpi_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}