<?php

/**
 * BaseEvenement_mris
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date_evenement
 * @property string $description
 * @property integer $dossier_these_id
 * @property integer $dossier_ere_id
 * @property integer $dossier_postdoc_id
 * @property integer $type_evenement_these_id
 * @property integer $type_evenement_ere_id
 * @property integer $type_evenement_postdoc_id
 * @property Dossier_these $Dossier_these
 * @property Dossier_ere $Dossier_ere
 * @property Dossier_postdoc $Dossier_postdoc
 * @property Type_evenement_these $Type_evenement_these
 * @property Type_evenement_ere $Type_evenement_ere
 * @property Type_evenement_postdoc $Type_evenement_postdoc
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method date                   getDateEvenement()             Returns the current record's "date_evenement" value
 * @method string                 getDescription()               Returns the current record's "description" value
 * @method integer                getDossierTheseId()            Returns the current record's "dossier_these_id" value
 * @method integer                getDossierEreId()              Returns the current record's "dossier_ere_id" value
 * @method integer                getDossierPostdocId()          Returns the current record's "dossier_postdoc_id" value
 * @method integer                getTypeEvenementTheseId()      Returns the current record's "type_evenement_these_id" value
 * @method integer                getTypeEvenementEreId()        Returns the current record's "type_evenement_ere_id" value
 * @method integer                getTypeEvenementPostdocId()    Returns the current record's "type_evenement_postdoc_id" value
 * @method Dossier_these          getDossierThese()              Returns the current record's "Dossier_these" value
 * @method Dossier_ere            getDossierEre()                Returns the current record's "Dossier_ere" value
 * @method Dossier_postdoc        getDossierPostdoc()            Returns the current record's "Dossier_postdoc" value
 * @method Type_evenement_these   getTypeEvenementThese()        Returns the current record's "Type_evenement_these" value
 * @method Type_evenement_ere     getTypeEvenementEre()          Returns the current record's "Type_evenement_ere" value
 * @method Type_evenement_postdoc getTypeEvenementPostdoc()      Returns the current record's "Type_evenement_postdoc" value
 * @method Utilisateur            getUtilisateurCreatedBy()      Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur            getUtilisateurUpdatedBy()      Returns the current record's "UtilisateurUpdatedBy" value
 * @method Evenement_mris         setDateEvenement()             Sets the current record's "date_evenement" value
 * @method Evenement_mris         setDescription()               Sets the current record's "description" value
 * @method Evenement_mris         setDossierTheseId()            Sets the current record's "dossier_these_id" value
 * @method Evenement_mris         setDossierEreId()              Sets the current record's "dossier_ere_id" value
 * @method Evenement_mris         setDossierPostdocId()          Sets the current record's "dossier_postdoc_id" value
 * @method Evenement_mris         setTypeEvenementTheseId()      Sets the current record's "type_evenement_these_id" value
 * @method Evenement_mris         setTypeEvenementEreId()        Sets the current record's "type_evenement_ere_id" value
 * @method Evenement_mris         setTypeEvenementPostdocId()    Sets the current record's "type_evenement_postdoc_id" value
 * @method Evenement_mris         setDossierThese()              Sets the current record's "Dossier_these" value
 * @method Evenement_mris         setDossierEre()                Sets the current record's "Dossier_ere" value
 * @method Evenement_mris         setDossierPostdoc()            Sets the current record's "Dossier_postdoc" value
 * @method Evenement_mris         setTypeEvenementThese()        Sets the current record's "Type_evenement_these" value
 * @method Evenement_mris         setTypeEvenementEre()          Sets the current record's "Type_evenement_ere" value
 * @method Evenement_mris         setTypeEvenementPostdoc()      Sets the current record's "Type_evenement_postdoc" value
 * @method Evenement_mris         setUtilisateurCreatedBy()      Sets the current record's "UtilisateurCreatedBy" value
 * @method Evenement_mris         setUtilisateurUpdatedBy()      Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEvenement_mris extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('evenement_mris');
        $this->hasColumn('date_evenement', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('dossier_these_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dossier_ere_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dossier_postdoc_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_evenement_these_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_evenement_ere_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_evenement_postdoc_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossier_these', array(
             'local' => 'dossier_these_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Dossier_ere', array(
             'local' => 'dossier_ere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Dossier_postdoc', array(
             'local' => 'dossier_postdoc_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Type_evenement_these', array(
             'local' => 'type_evenement_these_id',
             'foreign' => 'id'));

        $this->hasOne('Type_evenement_ere', array(
             'local' => 'type_evenement_ere_id',
             'foreign' => 'id'));

        $this->hasOne('Type_evenement_postdoc', array(
             'local' => 'type_evenement_postdoc_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}