<?php

/**
 * BaseRemarque_bpi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $contenu
 * @property integer $dossier_bpi_id
 * @property Dossier_bpi $Dossier_bpi
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method string       getContenu()              Returns the current record's "contenu" value
 * @method integer      getDossierBpiId()         Returns the current record's "dossier_bpi_id" value
 * @method Dossier_bpi  getDossierBpi()           Returns the current record's "Dossier_bpi" value
 * @method Utilisateur  getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur  getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Remarque_bpi setContenu()              Sets the current record's "contenu" value
 * @method Remarque_bpi setDossierBpiId()         Sets the current record's "dossier_bpi_id" value
 * @method Remarque_bpi setDossierBpi()           Sets the current record's "Dossier_bpi" value
 * @method Remarque_bpi setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Remarque_bpi setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRemarque_bpi extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('remarque_bpi');
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('dossier_bpi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossier_bpi', array(
             'local' => 'dossier_bpi_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}