<?php

/**
 * BaseEtat_partage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $Dossier_mip
 * @property Doctrine_Collection $Dossier_these
 * @property Doctrine_Collection $Dossier_ere
 * @property Doctrine_Collection $Dossier_postdoc
 * @property Doctrine_Collection $Dossier_bpi
 * @property Doctrine_Collection $View_recherche
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getIntitule()        Returns the current record's "intitule" value
 * @method Doctrine_Collection getDossierMip()      Returns the current record's "Dossier_mip" collection
 * @method Doctrine_Collection getDossierThese()    Returns the current record's "Dossier_these" collection
 * @method Doctrine_Collection getDossierEre()      Returns the current record's "Dossier_ere" collection
 * @method Doctrine_Collection getDossierPostdoc()  Returns the current record's "Dossier_postdoc" collection
 * @method Doctrine_Collection getDossierBpi()      Returns the current record's "Dossier_bpi" collection
 * @method Doctrine_Collection getViewRecherche()   Returns the current record's "View_recherche" collection
 * @method Etat_partage        setId()              Sets the current record's "id" value
 * @method Etat_partage        setIntitule()        Sets the current record's "intitule" value
 * @method Etat_partage        setDossierMip()      Sets the current record's "Dossier_mip" collection
 * @method Etat_partage        setDossierThese()    Sets the current record's "Dossier_these" collection
 * @method Etat_partage        setDossierEre()      Sets the current record's "Dossier_ere" collection
 * @method Etat_partage        setDossierPostdoc()  Sets the current record's "Dossier_postdoc" collection
 * @method Etat_partage        setDossierBpi()      Sets the current record's "Dossier_bpi" collection
 * @method Etat_partage        setViewRecherche()   Sets the current record's "View_recherche" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEtat_partage extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('etat_partage');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dossier_mip', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));

        $this->hasMany('Dossier_these', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));

        $this->hasMany('Dossier_ere', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));

        $this->hasMany('Dossier_postdoc', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));

        $this->hasMany('Dossier_bpi', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));

        $this->hasMany('View_recherche', array(
             'local' => 'id',
             'foreign' => 'etat_partage_id'));
    }
}