<?php

/**
 * BaseSession_invitation_commission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $invitation_id
 * @property integer $service_id
 * @property integer $laboratoire_id
 * @property string $transaction_token
 * @property boolean $est_concerne
 * @property Invitation $Invitation
 * @property Service $Service
 * @property Laboratoire $Laboratoire
 * 
 * @method integer                       getInvitationId()      Returns the current record's "invitation_id" value
 * @method integer                       getServiceId()         Returns the current record's "service_id" value
 * @method integer                       getLaboratoireId()     Returns the current record's "laboratoire_id" value
 * @method string                        getTransactionToken()  Returns the current record's "transaction_token" value
 * @method boolean                       getEstConcerne()       Returns the current record's "est_concerne" value
 * @method Invitation                    getInvitation()        Returns the current record's "Invitation" value
 * @method Service                       getService()           Returns the current record's "Service" value
 * @method Laboratoire                   getLaboratoire()       Returns the current record's "Laboratoire" value
 * @method Session_invitation_commission setInvitationId()      Sets the current record's "invitation_id" value
 * @method Session_invitation_commission setServiceId()         Sets the current record's "service_id" value
 * @method Session_invitation_commission setLaboratoireId()     Sets the current record's "laboratoire_id" value
 * @method Session_invitation_commission setTransactionToken()  Sets the current record's "transaction_token" value
 * @method Session_invitation_commission setEstConcerne()       Sets the current record's "est_concerne" value
 * @method Session_invitation_commission setInvitation()        Sets the current record's "Invitation" value
 * @method Session_invitation_commission setService()           Sets the current record's "Service" value
 * @method Session_invitation_commission setLaboratoire()       Sets the current record's "Laboratoire" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSession_invitation_commission extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('session_invitation_commission');
        $this->hasColumn('invitation_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('laboratoire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('transaction_token', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('est_concerne', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Invitation', array(
             'local' => 'invitation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Laboratoire', array(
             'local' => 'laboratoire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}