<?php

/**
 * BaseContentieux
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $part_inventive_id
 * @property integer $type_contentieux_id
 * @property boolean $est_desaccord
 * @property string $commentaire_desaccord
 * @property date $date_demande_cnis
 * @property date $date_cnis
 * @property string $decision_cnis
 * @property date $date_accord
 * @property Part_inventive $Part_inventive
 * @property Type_contentieux $Type_contentieux
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method integer          getId()                    Returns the current record's "id" value
 * @method integer          getPartInventiveId()       Returns the current record's "part_inventive_id" value
 * @method integer          getTypeContentieuxId()     Returns the current record's "type_contentieux_id" value
 * @method boolean          getEstDesaccord()          Returns the current record's "est_desaccord" value
 * @method string           getCommentaireDesaccord()  Returns the current record's "commentaire_desaccord" value
 * @method date             getDateDemandeCnis()       Returns the current record's "date_demande_cnis" value
 * @method date             getDateCnis()              Returns the current record's "date_cnis" value
 * @method string           getDecisionCnis()          Returns the current record's "decision_cnis" value
 * @method date             getDateAccord()            Returns the current record's "date_accord" value
 * @method Part_inventive   getPartInventive()         Returns the current record's "Part_inventive" value
 * @method Type_contentieux getTypeContentieux()       Returns the current record's "Type_contentieux" value
 * @method Utilisateur      getUtilisateurCreatedBy()  Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur      getUtilisateurUpdatedBy()  Returns the current record's "UtilisateurUpdatedBy" value
 * @method Contentieux      setId()                    Sets the current record's "id" value
 * @method Contentieux      setPartInventiveId()       Sets the current record's "part_inventive_id" value
 * @method Contentieux      setTypeContentieuxId()     Sets the current record's "type_contentieux_id" value
 * @method Contentieux      setEstDesaccord()          Sets the current record's "est_desaccord" value
 * @method Contentieux      setCommentaireDesaccord()  Sets the current record's "commentaire_desaccord" value
 * @method Contentieux      setDateDemandeCnis()       Sets the current record's "date_demande_cnis" value
 * @method Contentieux      setDateCnis()              Sets the current record's "date_cnis" value
 * @method Contentieux      setDecisionCnis()          Sets the current record's "decision_cnis" value
 * @method Contentieux      setDateAccord()            Sets the current record's "date_accord" value
 * @method Contentieux      setPartInventive()         Sets the current record's "Part_inventive" value
 * @method Contentieux      setTypeContentieux()       Sets the current record's "Type_contentieux" value
 * @method Contentieux      setUtilisateurCreatedBy()  Sets the current record's "UtilisateurCreatedBy" value
 * @method Contentieux      setUtilisateurUpdatedBy()  Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseContentieux extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('contentieux');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('part_inventive_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_contentieux_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('est_desaccord', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('commentaire_desaccord', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('date_demande_cnis', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_cnis', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('decision_cnis', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('date_accord', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Part_inventive', array(
             'local' => 'part_inventive_id',
             'foreign' => 'id'));

        $this->hasOne('Type_contentieux', array(
             'local' => 'type_contentieux_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}