<?php

/**
 * BaseCivilite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property string $abreviation
 * @property Doctrine_Collection $Utilisateur
 * @property Doctrine_Collection $Etudiant
 * @property Doctrine_Collection $Intervenant
 * @property Doctrine_Collection $Inventeur
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getIntitule()    Returns the current record's "intitule" value
 * @method string              getAbreviation() Returns the current record's "abreviation" value
 * @method Doctrine_Collection getUtilisateur() Returns the current record's "Utilisateur" collection
 * @method Doctrine_Collection getEtudiant()    Returns the current record's "Etudiant" collection
 * @method Doctrine_Collection getIntervenant() Returns the current record's "Intervenant" collection
 * @method Doctrine_Collection getInventeur()   Returns the current record's "Inventeur" collection
 * @method Civilite            setId()          Sets the current record's "id" value
 * @method Civilite            setIntitule()    Sets the current record's "intitule" value
 * @method Civilite            setAbreviation() Sets the current record's "abreviation" value
 * @method Civilite            setUtilisateur() Sets the current record's "Utilisateur" collection
 * @method Civilite            setEtudiant()    Sets the current record's "Etudiant" collection
 * @method Civilite            setIntervenant() Sets the current record's "Intervenant" collection
 * @method Civilite            setInventeur()   Sets the current record's "Inventeur" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCivilite extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('civilite');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abreviation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Utilisateur', array(
             'local' => 'id',
             'foreign' => 'civilite_id'));

        $this->hasMany('Etudiant', array(
             'local' => 'id',
             'foreign' => 'civilite_id'));

        $this->hasMany('Intervenant', array(
             'local' => 'id',
             'foreign' => 'civilite_id'));

        $this->hasMany('Inventeur', array(
             'local' => 'id',
             'foreign' => 'civilite_id'));
    }
}