<?php

/**
 * BaseVersement_dossier_these
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date_versement
 * @property float $montant_versement
 * @property integer $dossier_these_id
 * @property Dossier_these $DossierThese
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method date                    getDateVersement()        Returns the current record's "date_versement" value
 * @method float                   getMontantVersement()     Returns the current record's "montant_versement" value
 * @method integer                 getDossierTheseId()       Returns the current record's "dossier_these_id" value
 * @method Dossier_these           getDossierThese()         Returns the current record's "DossierThese" value
 * @method Utilisateur             getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur             getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Versement_dossier_these setDateVersement()        Sets the current record's "date_versement" value
 * @method Versement_dossier_these setMontantVersement()     Sets the current record's "montant_versement" value
 * @method Versement_dossier_these setDossierTheseId()       Sets the current record's "dossier_these_id" value
 * @method Versement_dossier_these setDossierThese()         Sets the current record's "DossierThese" value
 * @method Versement_dossier_these setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Versement_dossier_these setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseVersement_dossier_these extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('versement_dossier_these');
        $this->hasColumn('date_versement', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('montant_versement', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('dossier_these_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossier_these as DossierThese', array(
             'local' => 'dossier_these_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}