<?php

/**
 * BaseRole_ere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $Session_encadrants_dossier_ere
 * @property Doctrine_Collection $Encadrant_ere
 * 
 * @method integer             getId()                             Returns the current record's "id" value
 * @method string              getIntitule()                       Returns the current record's "intitule" value
 * @method Doctrine_Collection getSessionEncadrantsDossierEre()    Returns the current record's "Session_encadrants_dossier_ere" collection
 * @method Doctrine_Collection getEncadrantEre()                   Returns the current record's "Encadrant_ere" collection
 * @method Role_ere            setId()                             Sets the current record's "id" value
 * @method Role_ere            setIntitule()                       Sets the current record's "intitule" value
 * @method Role_ere            setSessionEncadrantsDossierEre()    Sets the current record's "Session_encadrants_dossier_ere" collection
 * @method Role_ere            setEncadrantEre()                   Sets the current record's "Encadrant_ere" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRole_ere extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('role_ere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Session_encadrants_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'role_ere_id'));

        $this->hasMany('Encadrant_ere', array(
             'local' => 'id',
             'foreign' => 'role_ere_id'));
    }
}