<?php

/**
 * BaseEcheance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date_echeance_ea
 * @property timestamp $date_echeance_cr
 * @property integer $dossier_mip_id
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Dossier_mip $Dossier_mip
 * 
 * @method timestamp   getDateEcheanceEa()       Returns the current record's "date_echeance_ea" value
 * @method timestamp   getDateEcheanceCr()       Returns the current record's "date_echeance_cr" value
 * @method integer     getDossierMipId()         Returns the current record's "dossier_mip_id" value
 * @method Utilisateur getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Dossier_mip getDossierMip()           Returns the current record's "Dossier_mip" value
 * @method Echeance    setDateEcheanceEa()       Sets the current record's "date_echeance_ea" value
 * @method Echeance    setDateEcheanceCr()       Sets the current record's "date_echeance_cr" value
 * @method Echeance    setDossierMipId()         Sets the current record's "dossier_mip_id" value
 * @method Echeance    setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Echeance    setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * @method Echeance    setDossierMip()           Sets the current record's "Dossier_mip" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEcheance extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('echeance');
        $this->hasColumn('date_echeance_ea', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_echeance_cr', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('dossier_mip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasOne('Dossier_mip', array(
             'local' => 'dossier_mip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}