<?php

/**
 * BaseSession_innovateur_dossier_mip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $innovateur_id
 * @property string $transaction_token
 * @property integer $nouveau_type_id
 * @property Utilisateur $Innovateur
 * @property Type_innovateur $Type_innovateur
 * 
 * @method integer                        getInnovateurId()      Returns the current record's "innovateur_id" value
 * @method string                         getTransactionToken()  Returns the current record's "transaction_token" value
 * @method integer                        getNouveauTypeId()     Returns the current record's "nouveau_type_id" value
 * @method Utilisateur                    getInnovateur()        Returns the current record's "Innovateur" value
 * @method Type_innovateur                getTypeInnovateur()    Returns the current record's "Type_innovateur" value
 * @method Session_innovateur_dossier_mip setInnovateurId()      Sets the current record's "innovateur_id" value
 * @method Session_innovateur_dossier_mip setTransactionToken()  Sets the current record's "transaction_token" value
 * @method Session_innovateur_dossier_mip setNouveauTypeId()     Sets the current record's "nouveau_type_id" value
 * @method Session_innovateur_dossier_mip setInnovateur()        Sets the current record's "Innovateur" value
 * @method Session_innovateur_dossier_mip setTypeInnovateur()    Sets the current record's "Type_innovateur" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSession_innovateur_dossier_mip extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('session_innovateur_dossier_mip');
        $this->hasColumn('innovateur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('transaction_token', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('nouveau_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as Innovateur', array(
             'local' => 'innovateur_id',
             'foreign' => 'id'));

        $this->hasOne('Type_innovateur', array(
             'local' => 'nouveau_type_id',
             'foreign' => 'id'));
    }
}