<?php

/**
 * BaseDossier_these_laboratoire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dossier_these_id
 * @property integer $laboratoire_id
 * @property Dossier_these $Dossier_these
 * @property Laboratoire $Laboratoire
 * 
 * @method integer                   getId()               Returns the current record's "id" value
 * @method integer                   getDossierTheseId()   Returns the current record's "dossier_these_id" value
 * @method integer                   getLaboratoireId()    Returns the current record's "laboratoire_id" value
 * @method Dossier_these             getDossierThese()     Returns the current record's "Dossier_these" value
 * @method Laboratoire               getLaboratoire()      Returns the current record's "Laboratoire" value
 * @method Dossier_these_laboratoire setId()               Sets the current record's "id" value
 * @method Dossier_these_laboratoire setDossierTheseId()   Sets the current record's "dossier_these_id" value
 * @method Dossier_these_laboratoire setLaboratoireId()    Sets the current record's "laboratoire_id" value
 * @method Dossier_these_laboratoire setDossierThese()     Sets the current record's "Dossier_these" value
 * @method Dossier_these_laboratoire setLaboratoire()      Sets the current record's "Laboratoire" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDossier_these_laboratoire extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('dossier_these_laboratoire');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dossier_these_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('laboratoire_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossier_these', array(
             'local' => 'dossier_these_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Laboratoire', array(
             'local' => 'laboratoire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}