<?php

/**
 * BaseContrat_type_contrat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contrat_id
 * @property integer $type_contrat_id
 * @property Contrat $Contrat
 * @property Type_contrat $Type_contrat
 * 
 * @method integer              getContratId()       Returns the current record's "contrat_id" value
 * @method integer              getTypeContratId()   Returns the current record's "type_contrat_id" value
 * @method Contrat              getContrat()         Returns the current record's "Contrat" value
 * @method Type_contrat         getTypeContrat()     Returns the current record's "Type_contrat" value
 * @method Contrat_type_contrat setContratId()       Sets the current record's "contrat_id" value
 * @method Contrat_type_contrat setTypeContratId()   Sets the current record's "type_contrat_id" value
 * @method Contrat_type_contrat setContrat()         Sets the current record's "Contrat" value
 * @method Contrat_type_contrat setTypeContrat()     Sets the current record's "Type_contrat" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseContrat_type_contrat extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('contrat_type_contrat');
        $this->hasColumn('contrat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('type_contrat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contrat', array(
             'local' => 'contrat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Type_contrat', array(
             'local' => 'type_contrat_id',
             'foreign' => 'id'));
    }
}