<?php

/**
 * BaseConvention_organisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numero_convention
 * @property integer $type_convention_organisme_id
 * @property integer $organisme_id
 * @property integer $montant
 * @property date $date_signature
 * @property date $date_notification
 * @property date $date_prise_effet
 * @property date $date_fin_effet
 * @property date $date_archivage
 * @property string $fichier
 * @property string $fichier_orig
 * @property Type_convention_organisme $TypeConventionOrganisme
 * @property Organisme $Organisme
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method string                    getNumeroConvention()             Returns the current record's "numero_convention" value
 * @method integer                   getTypeConventionOrganismeId()    Returns the current record's "type_convention_organisme_id" value
 * @method integer                   getOrganismeId()                  Returns the current record's "organisme_id" value
 * @method integer                   getMontant()                      Returns the current record's "montant" value
 * @method date                      getDateSignature()                Returns the current record's "date_signature" value
 * @method date                      getDateNotification()             Returns the current record's "date_notification" value
 * @method date                      getDatePriseEffet()               Returns the current record's "date_prise_effet" value
 * @method date                      getDateFinEffet()                 Returns the current record's "date_fin_effet" value
 * @method date                      getDateArchivage()                Returns the current record's "date_archivage" value
 * @method string                    getFichier()                      Returns the current record's "fichier" value
 * @method string                    getFichierOrig()                  Returns the current record's "fichier_orig" value
 * @method Type_convention_organisme getTypeConventionOrganisme()      Returns the current record's "TypeConventionOrganisme" value
 * @method Organisme                 getOrganisme()                    Returns the current record's "Organisme" value
 * @method Utilisateur               getUtilisateurCreatedBy()         Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur               getUtilisateurUpdatedBy()         Returns the current record's "UtilisateurUpdatedBy" value
 * @method Convention_organisme      setNumeroConvention()             Sets the current record's "numero_convention" value
 * @method Convention_organisme      setTypeConventionOrganismeId()    Sets the current record's "type_convention_organisme_id" value
 * @method Convention_organisme      setOrganismeId()                  Sets the current record's "organisme_id" value
 * @method Convention_organisme      setMontant()                      Sets the current record's "montant" value
 * @method Convention_organisme      setDateSignature()                Sets the current record's "date_signature" value
 * @method Convention_organisme      setDateNotification()             Sets the current record's "date_notification" value
 * @method Convention_organisme      setDatePriseEffet()               Sets the current record's "date_prise_effet" value
 * @method Convention_organisme      setDateFinEffet()                 Sets the current record's "date_fin_effet" value
 * @method Convention_organisme      setDateArchivage()                Sets the current record's "date_archivage" value
 * @method Convention_organisme      setFichier()                      Sets the current record's "fichier" value
 * @method Convention_organisme      setFichierOrig()                  Sets the current record's "fichier_orig" value
 * @method Convention_organisme      setTypeConventionOrganisme()      Sets the current record's "TypeConventionOrganisme" value
 * @method Convention_organisme      setOrganisme()                    Sets the current record's "Organisme" value
 * @method Convention_organisme      setUtilisateurCreatedBy()         Sets the current record's "UtilisateurCreatedBy" value
 * @method Convention_organisme      setUtilisateurUpdatedBy()         Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseConvention_organisme extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('convention_organisme');
        $this->hasColumn('numero_convention', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type_convention_organisme_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('montant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_signature', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_notification', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_prise_effet', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('date_fin_effet', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_archivage', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fichier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fichier_orig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Type_convention_organisme as TypeConventionOrganisme', array(
             'local' => 'type_convention_organisme_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}