<?php

/**
 * BasePays
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $abreviation
 * @property Doctrine_Collection $Point_contact
 * @property Doctrine_Collection $Etudiant
 * @property Doctrine_Collection $Intervenant
 * @property Doctrine_Collection $Brevet
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNom()           Returns the current record's "nom" value
 * @method string              getAbreviation()   Returns the current record's "abreviation" value
 * @method Doctrine_Collection getPointContact()  Returns the current record's "Point_contact" collection
 * @method Doctrine_Collection getEtudiant()      Returns the current record's "Etudiant" collection
 * @method Doctrine_Collection getIntervenant()   Returns the current record's "Intervenant" collection
 * @method Doctrine_Collection getBrevet()        Returns the current record's "Brevet" collection
 * @method Pays                setId()            Sets the current record's "id" value
 * @method Pays                setNom()           Sets the current record's "nom" value
 * @method Pays                setAbreviation()   Sets the current record's "abreviation" value
 * @method Pays                setPointContact()  Sets the current record's "Point_contact" collection
 * @method Pays                setEtudiant()      Sets the current record's "Etudiant" collection
 * @method Pays                setIntervenant()   Sets the current record's "Intervenant" collection
 * @method Pays                setBrevet()        Sets the current record's "Brevet" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePays extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pays');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abreviation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Point_contact', array(
             'local' => 'id',
             'foreign' => 'pays_id'));

        $this->hasMany('Etudiant', array(
             'local' => 'id',
             'foreign' => 'pays_id'));

        $this->hasMany('Intervenant', array(
             'local' => 'id',
             'foreign' => 'pays_id'));

        $this->hasMany('Brevet', array(
             'local' => 'id',
             'foreign' => 'pays_id'));
    }
}