<?php

/**
 * BaseStatut_projet_mip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property string $abreviation
 * @property Doctrine_Collection $Dossier_mip
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getIntitule()    Returns the current record's "intitule" value
 * @method string              getAbreviation() Returns the current record's "abreviation" value
 * @method Doctrine_Collection getDossierMip()  Returns the current record's "Dossier_mip" collection
 * @method Statut_projet_mip   setId()          Sets the current record's "id" value
 * @method Statut_projet_mip   setIntitule()    Sets the current record's "intitule" value
 * @method Statut_projet_mip   setAbreviation() Sets the current record's "abreviation" value
 * @method Statut_projet_mip   setDossierMip()  Sets the current record's "Dossier_mip" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseStatut_projet_mip extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('statut_projet_mip');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abreviation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dossier_mip', array(
             'local' => 'id',
             'foreign' => 'statut_projet_mip_id'));
    }
}