<?php

/**
 * BaseValorisation_interne
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date_debut_exploitation
 * @property integer $organisme_mindef_id
 * @property integer $valorisation_bpi_id
 * @property Organisme_mindef $Organisme_mindef
 * @property Valorisation_bpi $Valorisation_bpi
 * 
 * @method integer              getId()                      Returns the current record's "id" value
 * @method date                 getDateDebutExploitation()   Returns the current record's "date_debut_exploitation" value
 * @method integer              getOrganismeMindefId()       Returns the current record's "organisme_mindef_id" value
 * @method integer              getValorisationBpiId()       Returns the current record's "valorisation_bpi_id" value
 * @method Organisme_mindef     getOrganismeMindef()         Returns the current record's "Organisme_mindef" value
 * @method Valorisation_bpi     getValorisationBpi()         Returns the current record's "Valorisation_bpi" value
 * @method Valorisation_interne setId()                      Sets the current record's "id" value
 * @method Valorisation_interne setDateDebutExploitation()   Sets the current record's "date_debut_exploitation" value
 * @method Valorisation_interne setOrganismeMindefId()       Sets the current record's "organisme_mindef_id" value
 * @method Valorisation_interne setValorisationBpiId()       Sets the current record's "valorisation_bpi_id" value
 * @method Valorisation_interne setOrganismeMindef()         Sets the current record's "Organisme_mindef" value
 * @method Valorisation_interne setValorisationBpi()         Sets the current record's "Valorisation_bpi" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseValorisation_interne extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('valorisation_interne');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('date_debut_exploitation', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('organisme_mindef_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valorisation_bpi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organisme_mindef', array(
             'local' => 'organisme_mindef_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Valorisation_bpi', array(
             'local' => 'valorisation_bpi_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}