<?php

/**
 * BaseDomaine_scientifique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property boolean $est_actif
 * @property Doctrine_Collection $Utilisateurs
 * @property Doctrine_Collection $Utilisateur_domaine_scientifique
 * @property Doctrine_Collection $Dossier_these
 * @property Doctrine_Collection $Dossier_ere
 * @property Doctrine_Collection $Dossier_postdoc
 * 
 * @method integer              getId()                               Returns the current record's "id" value
 * @method string               getIntitule()                         Returns the current record's "intitule" value
 * @method boolean              getEstActif()                         Returns the current record's "est_actif" value
 * @method Doctrine_Collection  getUtilisateurs()                     Returns the current record's "Utilisateurs" collection
 * @method Doctrine_Collection  getUtilisateurDomaineScientifique()   Returns the current record's "Utilisateur_domaine_scientifique" collection
 * @method Doctrine_Collection  getDossierThese()                     Returns the current record's "Dossier_these" collection
 * @method Doctrine_Collection  getDossierEre()                       Returns the current record's "Dossier_ere" collection
 * @method Doctrine_Collection  getDossierPostdoc()                   Returns the current record's "Dossier_postdoc" collection
 * @method Domaine_scientifique setId()                               Sets the current record's "id" value
 * @method Domaine_scientifique setIntitule()                         Sets the current record's "intitule" value
 * @method Domaine_scientifique setEstActif()                         Sets the current record's "est_actif" value
 * @method Domaine_scientifique setUtilisateurs()                     Sets the current record's "Utilisateurs" collection
 * @method Domaine_scientifique setUtilisateurDomaineScientifique()   Sets the current record's "Utilisateur_domaine_scientifique" collection
 * @method Domaine_scientifique setDossierThese()                     Sets the current record's "Dossier_these" collection
 * @method Domaine_scientifique setDossierEre()                       Sets the current record's "Dossier_ere" collection
 * @method Domaine_scientifique setDossierPostdoc()                   Sets the current record's "Dossier_postdoc" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDomaine_scientifique extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('domaine_scientifique');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('est_actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Utilisateur as Utilisateurs', array(
             'refClass' => 'Utilisateur_domaine_scientifique',
             'local' => 'domaine_scientifique_id',
             'foreign' => 'utilisateur_id'));

        $this->hasMany('Utilisateur_domaine_scientifique', array(
             'local' => 'id',
             'foreign' => 'domaine_scientifique_id'));

        $this->hasMany('Dossier_these', array(
             'local' => 'id',
             'foreign' => 'domaine_scientifique_id'));

        $this->hasMany('Dossier_ere', array(
             'local' => 'id',
             'foreign' => 'domaine_scientifique_id'));

        $this->hasMany('Dossier_postdoc', array(
             'local' => 'id',
             'foreign' => 'domaine_scientifique_id'));
    }
}