<?php

/**
 * BaseEntite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $intitule
 * @property string $abreviation
 * @property string $lieu
 * @property integer $ville_id
 * @property integer $organisme_mindef_id
 * @property integer $entite_id
 * @property boolean $est_actif
 * @property string $parents
 * @property string $parents_arbo
 * @property boolean $est_executant
 * @property string $code_executant
 * @property Ville $Ville
 * @property Entite $Entite
 * @property Organisme_mindef $Organisme_mindef
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Doctrine_Collection $Utilisateur
 * @property Doctrine_Collection $SousEntites
 * @property Doctrine_Collection $Contact_se
 * @property Doctrine_Collection $Transfert_cloture
 * @property Doctrine_Collection $Inventeur
 * @property Doctrine_Collection $Dossier_bpi
 * @property Doctrine_Collection $Financement
 * @property Doctrine_Collection $Engagement
 * @property Doctrine_Collection $Paiement
 * 
 * @method string              getIntitule()             Returns the current record's "intitule" value
 * @method string              getAbreviation()          Returns the current record's "abreviation" value
 * @method string              getLieu()                 Returns the current record's "lieu" value
 * @method integer             getVilleId()              Returns the current record's "ville_id" value
 * @method integer             getOrganismeMindefId()    Returns the current record's "organisme_mindef_id" value
 * @method integer             getEntiteId()             Returns the current record's "entite_id" value
 * @method boolean             getEstActif()             Returns the current record's "est_actif" value
 * @method string              getParents()              Returns the current record's "parents" value
 * @method string              getParentsArbo()          Returns the current record's "parents_arbo" value
 * @method boolean             getEstExecutant()         Returns the current record's "est_executant" value
 * @method string              getCodeExecutant()        Returns the current record's "code_executant" value
 * @method Ville               getVille()                Returns the current record's "Ville" value
 * @method Entite              getEntite()               Returns the current record's "Entite" value
 * @method Organisme_mindef    getOrganismeMindef()      Returns the current record's "Organisme_mindef" value
 * @method Utilisateur         getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur         getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Doctrine_Collection getUtilisateur()          Returns the current record's "Utilisateur" collection
 * @method Doctrine_Collection getSousEntites()          Returns the current record's "SousEntites" collection
 * @method Doctrine_Collection getContactSe()            Returns the current record's "Contact_se" collection
 * @method Doctrine_Collection getTransfertCloture()     Returns the current record's "Transfert_cloture" collection
 * @method Doctrine_Collection getInventeur()            Returns the current record's "Inventeur" collection
 * @method Doctrine_Collection getDossierBpi()           Returns the current record's "Dossier_bpi" collection
 * @method Doctrine_Collection getFinancement()          Returns the current record's "Financement" collection
 * @method Doctrine_Collection getEngagement()           Returns the current record's "Engagement" collection
 * @method Doctrine_Collection getPaiement()             Returns the current record's "Paiement" collection
 * @method Entite              setIntitule()             Sets the current record's "intitule" value
 * @method Entite              setAbreviation()          Sets the current record's "abreviation" value
 * @method Entite              setLieu()                 Sets the current record's "lieu" value
 * @method Entite              setVilleId()              Sets the current record's "ville_id" value
 * @method Entite              setOrganismeMindefId()    Sets the current record's "organisme_mindef_id" value
 * @method Entite              setEntiteId()             Sets the current record's "entite_id" value
 * @method Entite              setEstActif()             Sets the current record's "est_actif" value
 * @method Entite              setParents()              Sets the current record's "parents" value
 * @method Entite              setParentsArbo()          Sets the current record's "parents_arbo" value
 * @method Entite              setEstExecutant()         Sets the current record's "est_executant" value
 * @method Entite              setCodeExecutant()        Sets the current record's "code_executant" value
 * @method Entite              setVille()                Sets the current record's "Ville" value
 * @method Entite              setEntite()               Sets the current record's "Entite" value
 * @method Entite              setOrganismeMindef()      Sets the current record's "Organisme_mindef" value
 * @method Entite              setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Entite              setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * @method Entite              setUtilisateur()          Sets the current record's "Utilisateur" collection
 * @method Entite              setSousEntites()          Sets the current record's "SousEntites" collection
 * @method Entite              setContactSe()            Sets the current record's "Contact_se" collection
 * @method Entite              setTransfertCloture()     Sets the current record's "Transfert_cloture" collection
 * @method Entite              setInventeur()            Sets the current record's "Inventeur" collection
 * @method Entite              setDossierBpi()           Sets the current record's "Dossier_bpi" collection
 * @method Entite              setFinancement()          Sets the current record's "Financement" collection
 * @method Entite              setEngagement()           Sets the current record's "Engagement" collection
 * @method Entite              setPaiement()             Sets the current record's "Paiement" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEntite extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('entite');
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abreviation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lieu', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ville_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisme_mindef_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entite_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('est_actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('parents', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('parents_arbo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('est_executant', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('code_executant', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ville', array(
             'local' => 'ville_id',
             'foreign' => 'id'));

        $this->hasOne('Entite', array(
             'local' => 'entite_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme_mindef', array(
             'local' => 'organisme_mindef_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Utilisateur', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Entite as SousEntites', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Contact_se', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Transfert_cloture', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Inventeur', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Dossier_bpi', array(
             'local' => 'id',
             'foreign' => 'autorite_decision_id'));

        $this->hasMany('Financement', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Engagement', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $this->hasMany('Paiement', array(
             'local' => 'id',
             'foreign' => 'entite_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}