<?php

/**
 * BaseContentieux_avec_tiers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organisme_id
 * @property integer $type_contentieux_tiers_id
 * @property boolean $est_desaccord
 * @property string $commentaire_desaccord
 * @property date $date_accord
 * @property Organisme $Organisme
 * @property Type_contentieux_tiers $Type_contentieux_tiers
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method integer                getId()                        Returns the current record's "id" value
 * @method integer                getOrganismeId()               Returns the current record's "organisme_id" value
 * @method integer                getTypeContentieuxTiersId()    Returns the current record's "type_contentieux_tiers_id" value
 * @method boolean                getEstDesaccord()              Returns the current record's "est_desaccord" value
 * @method string                 getCommentaireDesaccord()      Returns the current record's "commentaire_desaccord" value
 * @method date                   getDateAccord()                Returns the current record's "date_accord" value
 * @method Organisme              getOrganisme()                 Returns the current record's "Organisme" value
 * @method Type_contentieux_tiers getTypeContentieuxTiers()      Returns the current record's "Type_contentieux_tiers" value
 * @method Utilisateur            getUtilisateurCreatedBy()      Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur            getUtilisateurUpdatedBy()      Returns the current record's "UtilisateurUpdatedBy" value
 * @method Contentieux_avec_tiers setId()                        Sets the current record's "id" value
 * @method Contentieux_avec_tiers setOrganismeId()               Sets the current record's "organisme_id" value
 * @method Contentieux_avec_tiers setTypeContentieuxTiersId()    Sets the current record's "type_contentieux_tiers_id" value
 * @method Contentieux_avec_tiers setEstDesaccord()              Sets the current record's "est_desaccord" value
 * @method Contentieux_avec_tiers setCommentaireDesaccord()      Sets the current record's "commentaire_desaccord" value
 * @method Contentieux_avec_tiers setDateAccord()                Sets the current record's "date_accord" value
 * @method Contentieux_avec_tiers setOrganisme()                 Sets the current record's "Organisme" value
 * @method Contentieux_avec_tiers setTypeContentieuxTiers()      Sets the current record's "Type_contentieux_tiers" value
 * @method Contentieux_avec_tiers setUtilisateurCreatedBy()      Sets the current record's "UtilisateurCreatedBy" value
 * @method Contentieux_avec_tiers setUtilisateurUpdatedBy()      Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseContentieux_avec_tiers extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('contentieux_avec_tiers');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_contentieux_tiers_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('est_desaccord', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('commentaire_desaccord', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('date_accord', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasOne('Type_contentieux_tiers', array(
             'local' => 'type_contentieux_tiers_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}