<?php

/**
 * BaseSoutien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date_emission
 * @property string $reference
 * @property integer $dossier_mip_id
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Dossier_mip $Dossier_mip
 * 
 * @method timestamp   getDateEmission()         Returns the current record's "date_emission" value
 * @method string      getReference()            Returns the current record's "reference" value
 * @method integer     getDossierMipId()         Returns the current record's "dossier_mip_id" value
 * @method Utilisateur getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Dossier_mip getDossierMip()           Returns the current record's "Dossier_mip" value
 * @method Soutien     setDateEmission()         Sets the current record's "date_emission" value
 * @method Soutien     setReference()            Sets the current record's "reference" value
 * @method Soutien     setDossierMipId()         Sets the current record's "dossier_mip_id" value
 * @method Soutien     setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Soutien     setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * @method Soutien     setDossierMip()           Sets the current record's "Dossier_mip" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSoutien extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('soutien');
        $this->hasColumn('date_emission', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('reference', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dossier_mip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasOne('Dossier_mip', array(
             'local' => 'dossier_mip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}