<?php

/**
 * BaseDocuments_mip_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $Documents_mip
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getIntitule()      Returns the current record's "intitule" value
 * @method Doctrine_Collection getDocumentsMip()  Returns the current record's "Documents_mip" collection
 * @method Documents_mip_type  setId()            Sets the current record's "id" value
 * @method Documents_mip_type  setIntitule()      Sets the current record's "intitule" value
 * @method Documents_mip_type  setDocumentsMip()  Sets the current record's "Documents_mip" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDocuments_mip_type extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('documents_mip_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Documents_mip', array(
             'local' => 'id',
             'foreign' => 'documents_mip_type_id'));
    }
}