<?php

/**
 * BaseEngagement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type_engagement_id
 * @property date $date_engagement
 * @property float $montant
 * @property string $reference
 * @property integer $entite_id
 * @property integer $dossier_mip_id
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Type_engagement $Type_engagement
 * @property Dossier_mip $Dossier_mip
 * @property Entite $Entite
 * 
 * @method integer         getTypeEngagementId()     Returns the current record's "type_engagement_id" value
 * @method date            getDateEngagement()       Returns the current record's "date_engagement" value
 * @method float           getMontant()              Returns the current record's "montant" value
 * @method string          getReference()            Returns the current record's "reference" value
 * @method integer         getEntiteId()             Returns the current record's "entite_id" value
 * @method integer         getDossierMipId()         Returns the current record's "dossier_mip_id" value
 * @method Utilisateur     getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur     getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Type_engagement getTypeEngagement()       Returns the current record's "Type_engagement" value
 * @method Dossier_mip     getDossierMip()           Returns the current record's "Dossier_mip" value
 * @method Entite          getEntite()               Returns the current record's "Entite" value
 * @method Engagement      setTypeEngagementId()     Sets the current record's "type_engagement_id" value
 * @method Engagement      setDateEngagement()       Sets the current record's "date_engagement" value
 * @method Engagement      setMontant()              Sets the current record's "montant" value
 * @method Engagement      setReference()            Sets the current record's "reference" value
 * @method Engagement      setEntiteId()             Sets the current record's "entite_id" value
 * @method Engagement      setDossierMipId()         Sets the current record's "dossier_mip_id" value
 * @method Engagement      setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Engagement      setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * @method Engagement      setTypeEngagement()       Sets the current record's "Type_engagement" value
 * @method Engagement      setDossierMip()           Sets the current record's "Dossier_mip" value
 * @method Engagement      setEntite()               Sets the current record's "Entite" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEngagement extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('engagement');
        $this->hasColumn('type_engagement_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_engagement', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('montant', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('reference', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('entite_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dossier_mip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasOne('Type_engagement', array(
             'local' => 'type_engagement_id',
             'foreign' => 'id'));

        $this->hasOne('Dossier_mip', array(
             'local' => 'dossier_mip_id',
             'foreign' => 'id'));

        $this->hasOne('Entite', array(
             'local' => 'entite_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}