<?php

/**
 * BaseEvaluation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $note_id
 * @property integer $valeur_note_id
 * @property boolean $est_preselection
 * @property boolean $est_globale
 * @property boolean $est_actif
 * @property boolean $est_finale
 * @property integer $invitation_id
 * @property integer $dossier_these_id
 * @property integer $dossier_ere_id
 * @property integer $dossier_postdoc_id
 * @property Note $Note
 * @property Valeur_note $Valeur_note
 * @property Invitation $Invitation
 * @property Dossier_these $Dossier_these
 * @property Dossier_ere $Dossier_ere
 * @property Dossier_postdoc $Dossier_postdoc
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * 
 * @method integer         getNoteId()               Returns the current record's "note_id" value
 * @method integer         getValeurNoteId()         Returns the current record's "valeur_note_id" value
 * @method boolean         getEstPreselection()      Returns the current record's "est_preselection" value
 * @method boolean         getEstGlobale()           Returns the current record's "est_globale" value
 * @method boolean         getEstActif()             Returns the current record's "est_actif" value
 * @method boolean         getEstFinale()            Returns the current record's "est_finale" value
 * @method integer         getInvitationId()         Returns the current record's "invitation_id" value
 * @method integer         getDossierTheseId()       Returns the current record's "dossier_these_id" value
 * @method integer         getDossierEreId()         Returns the current record's "dossier_ere_id" value
 * @method integer         getDossierPostdocId()     Returns the current record's "dossier_postdoc_id" value
 * @method Note            getNote()                 Returns the current record's "Note" value
 * @method Valeur_note     getValeurNote()           Returns the current record's "Valeur_note" value
 * @method Invitation      getInvitation()           Returns the current record's "Invitation" value
 * @method Dossier_these   getDossierThese()         Returns the current record's "Dossier_these" value
 * @method Dossier_ere     getDossierEre()           Returns the current record's "Dossier_ere" value
 * @method Dossier_postdoc getDossierPostdoc()       Returns the current record's "Dossier_postdoc" value
 * @method Utilisateur     getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur     getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Evaluation      setNoteId()               Sets the current record's "note_id" value
 * @method Evaluation      setValeurNoteId()         Sets the current record's "valeur_note_id" value
 * @method Evaluation      setEstPreselection()      Sets the current record's "est_preselection" value
 * @method Evaluation      setEstGlobale()           Sets the current record's "est_globale" value
 * @method Evaluation      setEstActif()             Sets the current record's "est_actif" value
 * @method Evaluation      setEstFinale()            Sets the current record's "est_finale" value
 * @method Evaluation      setInvitationId()         Sets the current record's "invitation_id" value
 * @method Evaluation      setDossierTheseId()       Sets the current record's "dossier_these_id" value
 * @method Evaluation      setDossierEreId()         Sets the current record's "dossier_ere_id" value
 * @method Evaluation      setDossierPostdocId()     Sets the current record's "dossier_postdoc_id" value
 * @method Evaluation      setNote()                 Sets the current record's "Note" value
 * @method Evaluation      setValeurNote()           Sets the current record's "Valeur_note" value
 * @method Evaluation      setInvitation()           Sets the current record's "Invitation" value
 * @method Evaluation      setDossierThese()         Sets the current record's "Dossier_these" value
 * @method Evaluation      setDossierEre()           Sets the current record's "Dossier_ere" value
 * @method Evaluation      setDossierPostdoc()       Sets the current record's "Dossier_postdoc" value
 * @method Evaluation      setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Evaluation      setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEvaluation extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluation');
        $this->hasColumn('note_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('valeur_note_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('est_preselection', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('est_globale', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('est_actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('est_finale', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('invitation_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dossier_these_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dossier_ere_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dossier_postdoc_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Note', array(
             'local' => 'note_id',
             'foreign' => 'id'));

        $this->hasOne('Valeur_note', array(
             'local' => 'valeur_note_id',
             'foreign' => 'id'));

        $this->hasOne('Invitation', array(
             'local' => 'invitation_id',
             'foreign' => 'id'));

        $this->hasOne('Dossier_these', array(
             'local' => 'dossier_these_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Dossier_ere', array(
             'local' => 'dossier_ere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Dossier_postdoc', array(
             'local' => 'dossier_postdoc_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}