<?php

/**
 * BaseType_dossier_mris
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $Commission
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getIntitule()   Returns the current record's "intitule" value
 * @method Doctrine_Collection getCommission() Returns the current record's "Commission" collection
 * @method Type_dossier_mris   setId()         Sets the current record's "id" value
 * @method Type_dossier_mris   setIntitule()   Sets the current record's "intitule" value
 * @method Type_dossier_mris   setCommission() Sets the current record's "Commission" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseType_dossier_mris extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('type_dossier_mris');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Commission', array(
             'local' => 'id',
             'foreign' => 'type_dossier_mris_id'));
    }
}