<?php

/**
 * BaseDossier_ere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numero_provisoire
 * @property string $numero_definitif
 * @property string $titre
 * @property string $objet
 * @property string $fichier_editable
 * @property string $fichier_editable_orig
 * @property string $fichier_pdf
 * @property string $fichier_pdf_orig
 * @property integer $classement
 * @property boolean $est_actif
 * @property boolean $cotutelle
 * @property boolean $cooperation
 * @property integer $statut_dossier_ere_id
 * @property integer $domaine_scientifique_id
 * @property integer $organisme_mindef_id
 * @property integer $organisme_id
 * @property integer $realise_par
 * @property integer $pilote_par
 * @property integer $etat_partage_id
 * @property timestamp $mis_en_attente_le
 * @property string $repertoire_partage
 * @property Statut_dossier_ere $Statut_dossier_ere
 * @property Domaine_scientifique $Domaine_scientifique
 * @property Organisme_mindef $Organisme_mindef
 * @property Organisme $Organisme
 * @property Etat_partage $Etat_partage
 * @property Etudiant $Etudiant
 * @property Utilisateur $PilotePar
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Doctrine_Collection $Laboratoires
 * @property Aboutissement_ere $AboutissementEre
 * @property Doctrine_Collection $Session_encadrants_dossier_ere
 * @property Doctrine_Collection $Session_dossier_ere_laboratoire
 * @property Doctrine_Collection $Evaluation
 * @property Doctrine_Collection $Encadrant_ere
 * @property Doctrine_Collection $Dossier_ere_laboratoire
 * @property Doctrine_Collection $Suivi_dossier_ere
 * @property Doctrine_Collection $Evenement_mris
 * @property Doctrine_Collection $Document_mris
 * @property Doctrine_Collection $Remarque_mris
 * @property Doctrine_Collection $Avis_mris
 * @property Doctrine_Collection $Avis_mris_dossier_ere
 * @property Doctrine_Collection $View_recherche
 * @property Doctrine_Collection $Convention_dossier_ere
 * @property Doctrine_Collection $Versement_dossier_ere
 * 
 * @method string               getNumeroProvisoire()                Returns the current record's "numero_provisoire" value
 * @method string               getNumeroDefinitif()                 Returns the current record's "numero_definitif" value
 * @method string               getTitre()                           Returns the current record's "titre" value
 * @method string               getObjet()                           Returns the current record's "objet" value
 * @method string               getFichierEditable()                 Returns the current record's "fichier_editable" value
 * @method string               getFichierEditableOrig()             Returns the current record's "fichier_editable_orig" value
 * @method string               getFichierPdf()                      Returns the current record's "fichier_pdf" value
 * @method string               getFichierPdfOrig()                  Returns the current record's "fichier_pdf_orig" value
 * @method integer              getClassement()                      Returns the current record's "classement" value
 * @method boolean              getEstActif()                        Returns the current record's "est_actif" value
 * @method boolean              getCotutelle()                       Returns the current record's "cotutelle" value
 * @method boolean              getCooperation()                     Returns the current record's "cooperation" value
 * @method integer              getStatutDossierEreId()              Returns the current record's "statut_dossier_ere_id" value
 * @method integer              getDomaineScientifiqueId()           Returns the current record's "domaine_scientifique_id" value
 * @method integer              getOrganismeMindefId()               Returns the current record's "organisme_mindef_id" value
 * @method integer              getOrganismeId()                     Returns the current record's "organisme_id" value
 * @method integer              getRealisePar()                      Returns the current record's "realise_par" value
 * @method integer              getPilotePar()                       Returns the current record's "pilote_par" value
 * @method integer              getEtatPartageId()                   Returns the current record's "etat_partage_id" value
 * @method timestamp            getMisEnAttenteLe()                  Returns the current record's "mis_en_attente_le" value
 * @method string               getRepertoirePartage()               Returns the current record's "repertoire_partage" value
 * @method Statut_dossier_ere   getStatutDossierEre()                Returns the current record's "Statut_dossier_ere" value
 * @method Domaine_scientifique getDomaineScientifique()             Returns the current record's "Domaine_scientifique" value
 * @method Organisme_mindef     getOrganismeMindef()                 Returns the current record's "Organisme_mindef" value
 * @method Organisme            getOrganisme()                       Returns the current record's "Organisme" value
 * @method Etat_partage         getEtatPartage()                     Returns the current record's "Etat_partage" value
 * @method Etudiant             getEtudiant()                        Returns the current record's "Etudiant" value
 * @method Utilisateur          getPilotePar()                       Returns the current record's "PilotePar" value
 * @method Utilisateur          getUtilisateurCreatedBy()            Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur          getUtilisateurUpdatedBy()            Returns the current record's "UtilisateurUpdatedBy" value
 * @method Doctrine_Collection  getLaboratoires()                    Returns the current record's "Laboratoires" collection
 * @method Aboutissement_ere    getAboutissementEre()                Returns the current record's "AboutissementEre" value
 * @method Doctrine_Collection  getSessionEncadrantsDossierEre()     Returns the current record's "Session_encadrants_dossier_ere" collection
 * @method Doctrine_Collection  getSessionDossierEreLaboratoire()    Returns the current record's "Session_dossier_ere_laboratoire" collection
 * @method Doctrine_Collection  getEvaluation()                      Returns the current record's "Evaluation" collection
 * @method Doctrine_Collection  getEncadrantEre()                    Returns the current record's "Encadrant_ere" collection
 * @method Doctrine_Collection  getDossierEreLaboratoire()           Returns the current record's "Dossier_ere_laboratoire" collection
 * @method Doctrine_Collection  getSuiviDossierEre()                 Returns the current record's "Suivi_dossier_ere" collection
 * @method Doctrine_Collection  getEvenementMris()                   Returns the current record's "Evenement_mris" collection
 * @method Doctrine_Collection  getDocumentMris()                    Returns the current record's "Document_mris" collection
 * @method Doctrine_Collection  getRemarqueMris()                    Returns the current record's "Remarque_mris" collection
 * @method Doctrine_Collection  getAvisMris()                        Returns the current record's "Avis_mris" collection
 * @method Doctrine_Collection  getAvisMrisDossierEre()              Returns the current record's "Avis_mris_dossier_ere" collection
 * @method Doctrine_Collection  getViewRecherche()                   Returns the current record's "View_recherche" collection
 * @method Doctrine_Collection  getConventionDossierEre()            Returns the current record's "Convention_dossier_ere" collection
 * @method Doctrine_Collection  getVersementDossierEre()             Returns the current record's "Versement_dossier_ere" collection
 * @method Dossier_ere          setNumeroProvisoire()                Sets the current record's "numero_provisoire" value
 * @method Dossier_ere          setNumeroDefinitif()                 Sets the current record's "numero_definitif" value
 * @method Dossier_ere          setTitre()                           Sets the current record's "titre" value
 * @method Dossier_ere          setObjet()                           Sets the current record's "objet" value
 * @method Dossier_ere          setFichierEditable()                 Sets the current record's "fichier_editable" value
 * @method Dossier_ere          setFichierEditableOrig()             Sets the current record's "fichier_editable_orig" value
 * @method Dossier_ere          setFichierPdf()                      Sets the current record's "fichier_pdf" value
 * @method Dossier_ere          setFichierPdfOrig()                  Sets the current record's "fichier_pdf_orig" value
 * @method Dossier_ere          setClassement()                      Sets the current record's "classement" value
 * @method Dossier_ere          setEstActif()                        Sets the current record's "est_actif" value
 * @method Dossier_ere          setCotutelle()                       Sets the current record's "cotutelle" value
 * @method Dossier_ere          setCooperation()                     Sets the current record's "cooperation" value
 * @method Dossier_ere          setStatutDossierEreId()              Sets the current record's "statut_dossier_ere_id" value
 * @method Dossier_ere          setDomaineScientifiqueId()           Sets the current record's "domaine_scientifique_id" value
 * @method Dossier_ere          setOrganismeMindefId()               Sets the current record's "organisme_mindef_id" value
 * @method Dossier_ere          setOrganismeId()                     Sets the current record's "organisme_id" value
 * @method Dossier_ere          setRealisePar()                      Sets the current record's "realise_par" value
 * @method Dossier_ere          setPilotePar()                       Sets the current record's "pilote_par" value
 * @method Dossier_ere          setEtatPartageId()                   Sets the current record's "etat_partage_id" value
 * @method Dossier_ere          setMisEnAttenteLe()                  Sets the current record's "mis_en_attente_le" value
 * @method Dossier_ere          setRepertoirePartage()               Sets the current record's "repertoire_partage" value
 * @method Dossier_ere          setStatutDossierEre()                Sets the current record's "Statut_dossier_ere" value
 * @method Dossier_ere          setDomaineScientifique()             Sets the current record's "Domaine_scientifique" value
 * @method Dossier_ere          setOrganismeMindef()                 Sets the current record's "Organisme_mindef" value
 * @method Dossier_ere          setOrganisme()                       Sets the current record's "Organisme" value
 * @method Dossier_ere          setEtatPartage()                     Sets the current record's "Etat_partage" value
 * @method Dossier_ere          setEtudiant()                        Sets the current record's "Etudiant" value
 * @method Dossier_ere          setPilotePar()                       Sets the current record's "PilotePar" value
 * @method Dossier_ere          setUtilisateurCreatedBy()            Sets the current record's "UtilisateurCreatedBy" value
 * @method Dossier_ere          setUtilisateurUpdatedBy()            Sets the current record's "UtilisateurUpdatedBy" value
 * @method Dossier_ere          setLaboratoires()                    Sets the current record's "Laboratoires" collection
 * @method Dossier_ere          setAboutissementEre()                Sets the current record's "AboutissementEre" value
 * @method Dossier_ere          setSessionEncadrantsDossierEre()     Sets the current record's "Session_encadrants_dossier_ere" collection
 * @method Dossier_ere          setSessionDossierEreLaboratoire()    Sets the current record's "Session_dossier_ere_laboratoire" collection
 * @method Dossier_ere          setEvaluation()                      Sets the current record's "Evaluation" collection
 * @method Dossier_ere          setEncadrantEre()                    Sets the current record's "Encadrant_ere" collection
 * @method Dossier_ere          setDossierEreLaboratoire()           Sets the current record's "Dossier_ere_laboratoire" collection
 * @method Dossier_ere          setSuiviDossierEre()                 Sets the current record's "Suivi_dossier_ere" collection
 * @method Dossier_ere          setEvenementMris()                   Sets the current record's "Evenement_mris" collection
 * @method Dossier_ere          setDocumentMris()                    Sets the current record's "Document_mris" collection
 * @method Dossier_ere          setRemarqueMris()                    Sets the current record's "Remarque_mris" collection
 * @method Dossier_ere          setAvisMris()                        Sets the current record's "Avis_mris" collection
 * @method Dossier_ere          setAvisMrisDossierEre()              Sets the current record's "Avis_mris_dossier_ere" collection
 * @method Dossier_ere          setViewRecherche()                   Sets the current record's "View_recherche" collection
 * @method Dossier_ere          setConventionDossierEre()            Sets the current record's "Convention_dossier_ere" collection
 * @method Dossier_ere          setVersementDossierEre()             Sets the current record's "Versement_dossier_ere" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDossier_ere extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('dossier_ere');
        $this->hasColumn('numero_provisoire', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('numero_definitif', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('objet', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('fichier_editable', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fichier_editable_orig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fichier_pdf', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fichier_pdf_orig', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('classement', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('est_actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('cotutelle', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('cooperation', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('statut_dossier_ere_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('domaine_scientifique_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisme_mindef_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('realise_par', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pilote_par', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('etat_partage_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('mis_en_attente_le', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('repertoire_partage', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Statut_dossier_ere', array(
             'local' => 'statut_dossier_ere_id',
             'foreign' => 'id'));

        $this->hasOne('Domaine_scientifique', array(
             'local' => 'domaine_scientifique_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme_mindef', array(
             'local' => 'organisme_mindef_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasOne('Etat_partage', array(
             'local' => 'etat_partage_id',
             'foreign' => 'id'));

        $this->hasOne('Etudiant', array(
             'local' => 'realise_par',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur as PilotePar', array(
             'local' => 'pilote_par',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Laboratoire as Laboratoires', array(
             'refClass' => 'Dossier_ere_laboratoire',
             'local' => 'dossier_ere_id',
             'foreign' => 'laboratoire_id'));

        $this->hasOne('Aboutissement_ere as AboutissementEre', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Session_encadrants_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Session_dossier_ere_laboratoire', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Evaluation', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Encadrant_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Dossier_ere_laboratoire', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Suivi_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Evenement_mris', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Document_mris', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Remarque_mris', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Avis_mris', array(
             'refClass' => 'Avis_mris_dossier_ere',
             'local' => 'dossier_ere_id',
             'foreign' => 'avis_mris_id'));

        $this->hasMany('Avis_mris_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('View_recherche', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Convention_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $this->hasMany('Versement_dossier_ere', array(
             'local' => 'id',
             'foreign' => 'dossier_ere_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}