<?php

/**
 * BaseLibelle_organisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle_simple
 * @property string $libelle_liste
 * @property integer $metier_id
 * @property integer $organisme_mindef_id
 * @property Metier $Metier
 * @property Organisme_mindef $Organisme_mindef
 * 
 * @method integer           getId()                  Returns the current record's "id" value
 * @method string            getLibelleSimple()       Returns the current record's "libelle_simple" value
 * @method string            getLibelleListe()        Returns the current record's "libelle_liste" value
 * @method integer           getMetierId()            Returns the current record's "metier_id" value
 * @method integer           getOrganismeMindefId()   Returns the current record's "organisme_mindef_id" value
 * @method Metier            getMetier()              Returns the current record's "Metier" value
 * @method Organisme_mindef  getOrganismeMindef()     Returns the current record's "Organisme_mindef" value
 * @method Libelle_organisme setId()                  Sets the current record's "id" value
 * @method Libelle_organisme setLibelleSimple()       Sets the current record's "libelle_simple" value
 * @method Libelle_organisme setLibelleListe()        Sets the current record's "libelle_liste" value
 * @method Libelle_organisme setMetierId()            Sets the current record's "metier_id" value
 * @method Libelle_organisme setOrganismeMindefId()   Sets the current record's "organisme_mindef_id" value
 * @method Libelle_organisme setMetier()              Sets the current record's "Metier" value
 * @method Libelle_organisme setOrganismeMindef()     Sets the current record's "Organisme_mindef" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLibelle_organisme extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('libelle_organisme');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('libelle_simple', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('libelle_liste', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('metier_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('organisme_mindef_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Metier', array(
             'local' => 'metier_id',
             'foreign' => 'id'));

        $this->hasOne('Organisme_mindef', array(
             'local' => 'organisme_mindef_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}