<?php

/**
 * BaseTache
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cle
 * @property timestamp $debut
 * @property timestamp $fin
 * @property integer $pid
 * @property boolean $erreur
 * @property string $resultat
 * 
 * @method string    getCle()      Returns the current record's "cle" value
 * @method timestamp getDebut()    Returns the current record's "debut" value
 * @method timestamp getFin()      Returns the current record's "fin" value
 * @method integer   getPid()      Returns the current record's "pid" value
 * @method boolean   getErreur()   Returns the current record's "erreur" value
 * @method string    getResultat() Returns the current record's "resultat" value
 * @method Tache     setCle()      Sets the current record's "cle" value
 * @method Tache     setDebut()    Sets the current record's "debut" value
 * @method Tache     setFin()      Sets the current record's "fin" value
 * @method Tache     setPid()      Sets the current record's "pid" value
 * @method Tache     setErreur()   Sets the current record's "erreur" value
 * @method Tache     setResultat() Sets the current record's "resultat" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTache extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tache');
        $this->hasColumn('cle', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('debut', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fin', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('pid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('erreur', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('resultat', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}