<?php

/**
 * BaseSession_valorisation_externe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contrat_id
 * @property integer $organisme_id
 * @property integer $statut_valorisation_externe_id
 * @property string $transaction_token
 * @property Contrat $Contrat
 * @property Organisme $Organisme
 * @property Statut_valorisation_externe $StatutValorisationExterne
 * 
 * @method integer                      getContratId()                      Returns the current record's "contrat_id" value
 * @method integer                      getOrganismeId()                    Returns the current record's "organisme_id" value
 * @method integer                      getStatutValorisationExterneId()    Returns the current record's "statut_valorisation_externe_id" value
 * @method string                       getTransactionToken()               Returns the current record's "transaction_token" value
 * @method Contrat                      getContrat()                        Returns the current record's "Contrat" value
 * @method Organisme                    getOrganisme()                      Returns the current record's "Organisme" value
 * @method Statut_valorisation_externe  getStatutValorisationExterne()      Returns the current record's "StatutValorisationExterne" value
 * @method Session_valorisation_externe setContratId()                      Sets the current record's "contrat_id" value
 * @method Session_valorisation_externe setOrganismeId()                    Sets the current record's "organisme_id" value
 * @method Session_valorisation_externe setStatutValorisationExterneId()    Sets the current record's "statut_valorisation_externe_id" value
 * @method Session_valorisation_externe setTransactionToken()               Sets the current record's "transaction_token" value
 * @method Session_valorisation_externe setContrat()                        Sets the current record's "Contrat" value
 * @method Session_valorisation_externe setOrganisme()                      Sets the current record's "Organisme" value
 * @method Session_valorisation_externe setStatutValorisationExterne()      Sets the current record's "StatutValorisationExterne" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSession_valorisation_externe extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('session_valorisation_externe');
        $this->hasColumn('contrat_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organisme_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('statut_valorisation_externe_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('transaction_token', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contrat', array(
             'local' => 'contrat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Statut_valorisation_externe as StatutValorisationExterne', array(
             'local' => 'statut_valorisation_externe_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}