<?php

/**
 * BaseOrganisme_mindef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $intitule
 * @property string $abreviation
 * @property string $code
 * @property boolean $est_actif
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Doctrine_Collection $Utilisateur
 * @property Doctrine_Collection $Entite
 * @property Doctrine_Collection $Grade
 * @property Doctrine_Collection $Dossier_mip
 * @property Doctrine_Collection $Session_valorisation_interne
 * @property Doctrine_Collection $Dossier_these
 * @property Doctrine_Collection $Dossier_ere
 * @property Doctrine_Collection $Dossier_postdoc
 * @property Doctrine_Collection $Inventeur
 * @property Doctrine_Collection $Valorisation_interne
 * @property Doctrine_Collection $Libelle_organisme
 * 
 * @method string              getIntitule()                     Returns the current record's "intitule" value
 * @method string              getAbreviation()                  Returns the current record's "abreviation" value
 * @method string              getCode()                         Returns the current record's "code" value
 * @method boolean             getEstActif()                     Returns the current record's "est_actif" value
 * @method Utilisateur         getUtilisateurCreatedBy()         Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur         getUtilisateurUpdatedBy()         Returns the current record's "UtilisateurUpdatedBy" value
 * @method Doctrine_Collection getUtilisateur()                  Returns the current record's "Utilisateur" collection
 * @method Doctrine_Collection getEntite()                       Returns the current record's "Entite" collection
 * @method Doctrine_Collection getGrade()                        Returns the current record's "Grade" collection
 * @method Doctrine_Collection getDossierMip()                   Returns the current record's "Dossier_mip" collection
 * @method Doctrine_Collection getSessionValorisationInterne()   Returns the current record's "Session_valorisation_interne" collection
 * @method Doctrine_Collection getDossierThese()                 Returns the current record's "Dossier_these" collection
 * @method Doctrine_Collection getDossierEre()                   Returns the current record's "Dossier_ere" collection
 * @method Doctrine_Collection getDossierPostdoc()               Returns the current record's "Dossier_postdoc" collection
 * @method Doctrine_Collection getInventeur()                    Returns the current record's "Inventeur" collection
 * @method Doctrine_Collection getValorisationInterne()          Returns the current record's "Valorisation_interne" collection
 * @method Doctrine_Collection getLibelleOrganisme()             Returns the current record's "Libelle_organisme" collection
 * @method Organisme_mindef    setIntitule()                     Sets the current record's "intitule" value
 * @method Organisme_mindef    setAbreviation()                  Sets the current record's "abreviation" value
 * @method Organisme_mindef    setCode()                         Sets the current record's "code" value
 * @method Organisme_mindef    setEstActif()                     Sets the current record's "est_actif" value
 * @method Organisme_mindef    setUtilisateurCreatedBy()         Sets the current record's "UtilisateurCreatedBy" value
 * @method Organisme_mindef    setUtilisateurUpdatedBy()         Sets the current record's "UtilisateurUpdatedBy" value
 * @method Organisme_mindef    setUtilisateur()                  Sets the current record's "Utilisateur" collection
 * @method Organisme_mindef    setEntite()                       Sets the current record's "Entite" collection
 * @method Organisme_mindef    setGrade()                        Sets the current record's "Grade" collection
 * @method Organisme_mindef    setDossierMip()                   Sets the current record's "Dossier_mip" collection
 * @method Organisme_mindef    setSessionValorisationInterne()   Sets the current record's "Session_valorisation_interne" collection
 * @method Organisme_mindef    setDossierThese()                 Sets the current record's "Dossier_these" collection
 * @method Organisme_mindef    setDossierEre()                   Sets the current record's "Dossier_ere" collection
 * @method Organisme_mindef    setDossierPostdoc()               Sets the current record's "Dossier_postdoc" collection
 * @method Organisme_mindef    setInventeur()                    Sets the current record's "Inventeur" collection
 * @method Organisme_mindef    setValorisationInterne()          Sets the current record's "Valorisation_interne" collection
 * @method Organisme_mindef    setLibelleOrganisme()             Sets the current record's "Libelle_organisme" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseOrganisme_mindef extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('organisme_mindef');
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abreviation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('est_actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Utilisateur', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Entite', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Grade', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Dossier_mip', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Session_valorisation_interne', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Dossier_these', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Dossier_ere', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Dossier_postdoc', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Inventeur', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Valorisation_interne', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $this->hasMany('Libelle_organisme', array(
             'local' => 'id',
             'foreign' => 'organisme_mindef_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}