<?php

/**
 * BaseAvis_etatmajor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date_demande
 * @property string $reference_demande
 * @property timestamp $date_reception
 * @property timestamp $date_envoi
 * @property string $reference
 * @property boolean $est_favorable
 * @property string $recommandation
 * @property integer $dossier_mip_id
 * @property Utilisateur $UtilisateurCreatedBy
 * @property Utilisateur $UtilisateurUpdatedBy
 * @property Dossier_mip $Dossier_mip
 * 
 * @method timestamp      getDateDemande()          Returns the current record's "date_demande" value
 * @method string         getReferenceDemande()     Returns the current record's "reference_demande" value
 * @method timestamp      getDateReception()        Returns the current record's "date_reception" value
 * @method timestamp      getDateEnvoi()            Returns the current record's "date_envoi" value
 * @method string         getReference()            Returns the current record's "reference" value
 * @method boolean        getEstFavorable()         Returns the current record's "est_favorable" value
 * @method string         getRecommandation()       Returns the current record's "recommandation" value
 * @method integer        getDossierMipId()         Returns the current record's "dossier_mip_id" value
 * @method Utilisateur    getUtilisateurCreatedBy() Returns the current record's "UtilisateurCreatedBy" value
 * @method Utilisateur    getUtilisateurUpdatedBy() Returns the current record's "UtilisateurUpdatedBy" value
 * @method Dossier_mip    getDossierMip()           Returns the current record's "Dossier_mip" value
 * @method Avis_etatmajor setDateDemande()          Sets the current record's "date_demande" value
 * @method Avis_etatmajor setReferenceDemande()     Sets the current record's "reference_demande" value
 * @method Avis_etatmajor setDateReception()        Sets the current record's "date_reception" value
 * @method Avis_etatmajor setDateEnvoi()            Sets the current record's "date_envoi" value
 * @method Avis_etatmajor setReference()            Sets the current record's "reference" value
 * @method Avis_etatmajor setEstFavorable()         Sets the current record's "est_favorable" value
 * @method Avis_etatmajor setRecommandation()       Sets the current record's "recommandation" value
 * @method Avis_etatmajor setDossierMipId()         Sets the current record's "dossier_mip_id" value
 * @method Avis_etatmajor setUtilisateurCreatedBy() Sets the current record's "UtilisateurCreatedBy" value
 * @method Avis_etatmajor setUtilisateurUpdatedBy() Sets the current record's "UtilisateurUpdatedBy" value
 * @method Avis_etatmajor setDossierMip()           Sets the current record's "Dossier_mip" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAvis_etatmajor extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('avis_etatmajor');
        $this->hasColumn('date_demande', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('reference_demande', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_reception', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_envoi', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('reference', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('est_favorable', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('recommandation', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('dossier_mip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as UtilisateurCreatedBy', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as UtilisateurUpdatedBy', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasOne('Dossier_mip', array(
             'local' => 'dossier_mip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}