<?php

/**
 * BaseCommission_utilisateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $commission_id
 * @property integer $utilisateur_id
 * @property Commission $Commission
 * @property Utilisateur $Utilisateur
 * 
 * @method integer                getCommissionId()   Returns the current record's "commission_id" value
 * @method integer                getUtilisateurId()  Returns the current record's "utilisateur_id" value
 * @method Commission             getCommission()     Returns the current record's "Commission" value
 * @method Utilisateur            getUtilisateur()    Returns the current record's "Utilisateur" value
 * @method Commission_utilisateur setCommissionId()   Sets the current record's "commission_id" value
 * @method Commission_utilisateur setUtilisateurId()  Sets the current record's "utilisateur_id" value
 * @method Commission_utilisateur setCommission()     Sets the current record's "Commission" value
 * @method Commission_utilisateur setUtilisateur()    Sets the current record's "Utilisateur" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCommission_utilisateur extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('commission_utilisateur');
        $this->hasColumn('commission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commission', array(
             'local' => 'commission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'id'));
    }
}