<?php

/**
 * BaseEncadrant_postdoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dossier_postdoc_id
 * @property integer $intervenant_id
 * @property integer $role_postdoc_id
 * @property Dossier_postdoc $Dossier_postdoc
 * @property Intervenant $Intervenant
 * @property Role_postdoc $Role_postdoc
 * 
 * @method integer           getId()                 Returns the current record's "id" value
 * @method integer           getDossierPostdocId()   Returns the current record's "dossier_postdoc_id" value
 * @method integer           getIntervenantId()      Returns the current record's "intervenant_id" value
 * @method integer           getRolePostdocId()      Returns the current record's "role_postdoc_id" value
 * @method Dossier_postdoc   getDossierPostdoc()     Returns the current record's "Dossier_postdoc" value
 * @method Intervenant       getIntervenant()        Returns the current record's "Intervenant" value
 * @method Role_postdoc      getRolePostdoc()        Returns the current record's "Role_postdoc" value
 * @method Encadrant_postdoc setId()                 Sets the current record's "id" value
 * @method Encadrant_postdoc setDossierPostdocId()   Sets the current record's "dossier_postdoc_id" value
 * @method Encadrant_postdoc setIntervenantId()      Sets the current record's "intervenant_id" value
 * @method Encadrant_postdoc setRolePostdocId()      Sets the current record's "role_postdoc_id" value
 * @method Encadrant_postdoc setDossierPostdoc()     Sets the current record's "Dossier_postdoc" value
 * @method Encadrant_postdoc setIntervenant()        Sets the current record's "Intervenant" value
 * @method Encadrant_postdoc setRolePostdoc()        Sets the current record's "Role_postdoc" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEncadrant_postdoc extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('encadrant_postdoc');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dossier_postdoc_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('intervenant_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_postdoc_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossier_postdoc', array(
             'local' => 'dossier_postdoc_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Intervenant', array(
             'local' => 'intervenant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Role_postdoc', array(
             'local' => 'role_postdoc_id',
             'foreign' => 'id'));
    }
}