<?php

/**
 * BaseType_innovateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $Innovateur_dossier_mip
 * @property Doctrine_Collection $Session_innovateur_dossier_mip
 * 
 * @method integer             getId()                             Returns the current record's "id" value
 * @method string              getIntitule()                       Returns the current record's "intitule" value
 * @method Doctrine_Collection getInnovateurDossierMip()           Returns the current record's "Innovateur_dossier_mip" collection
 * @method Doctrine_Collection getSessionInnovateurDossierMip()    Returns the current record's "Session_innovateur_dossier_mip" collection
 * @method Type_innovateur     setId()                             Sets the current record's "id" value
 * @method Type_innovateur     setIntitule()                       Sets the current record's "intitule" value
 * @method Type_innovateur     setInnovateurDossierMip()           Sets the current record's "Innovateur_dossier_mip" collection
 * @method Type_innovateur     setSessionInnovateurDossierMip()    Sets the current record's "Session_innovateur_dossier_mip" collection
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseType_innovateur extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('type_innovateur');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Innovateur_dossier_mip', array(
             'local' => 'id',
             'foreign' => 'type_innovateur_id'));

        $this->hasMany('Session_innovateur_dossier_mip', array(
             'local' => 'id',
             'foreign' => 'nouveau_type_id'));
    }
}