<?php

/**
 * BaseFtp_recuperation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom_dossier
 * @property timestamp $date_debut
 * @property timestamp $date_fin
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getNomDossier()  Returns the current record's "nom_dossier" value
 * @method timestamp        getDateDebut()   Returns the current record's "date_debut" value
 * @method timestamp        getDateFin()     Returns the current record's "date_fin" value
 * @method Ftp_recuperation setId()          Sets the current record's "id" value
 * @method Ftp_recuperation setNomDossier()  Sets the current record's "nom_dossier" value
 * @method Ftp_recuperation setDateDebut()   Sets the current record's "date_debut" value
 * @method Ftp_recuperation setDateFin()     Sets the current record's "date_fin" value
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFtp_recuperation extends gridDoctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ftp_recuperation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom_dossier', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('date_debut', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_fin', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}