# page d'accueil
accueil:
  url:   /
  param: { module: interface, action: index }

# page de se connecter
seconnecter:
  url: /authentification/seconnecter
  param: { module: authentification, action: seconnecter }

deconnecter:
  url: /authentification/deconnecter
  param: { module: authentification, action: deconnecter }

# page d'erreur de droit
non_autorise:
  url: /authentification/nonAutorise
  param: { module: authentification, action: nonAutorise }


# pade d'accueil d'un module
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
