<?php

/**
 * Aboutissement_ereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Aboutissement_ereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Aboutissement_ereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aboutissement_ere');
    }
}