<?php

/**
 * Aboutissement_theseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Aboutissement_theseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Aboutissement_theseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aboutissement_these');
    }
}