<?php

/**
 * ClassementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassementTable extends Doctrine_Table
{

  /**
     * Returns an instance of this class.
     *
     * @return object ClassementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Classement');
    }
//
//    public function retrieveClassementByDossierId($intDossierBpiId)
//    {
//        $objRequeteDoctrine = $this->createQuery('c')->innerJoin('c.Classement_invention_final r ON r.classement_id = c.id')
//                                                     ->where('r.dossier_bpi_id = ?', $intDossierBpiId);
//
//        return $objRequeteDoctrine->execute();
//    }
}