<?php

/**
 * Convention_dossier_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Convention_dossier_postdocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Convention_dossier_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Convention_dossier_postdoc');
    }
}