<?php

/**
 * Documents_bpiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Documents_bpiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Documents_bpiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documents_bpi');
    }

    public function retrieveDocumentsByDossier($intDossierId,$boolEstJoint)
    {
      $q = Doctrine_Query::create()
        -> from ('Documents_bpi d')
        -> where('d.dossier_bpi_id = ?',$intDossierId)
        -> andWhere('d.est_joint = ?',$boolEstJoint)
        -> orderBy('created_at');

        return $q ->execute();
    }
    
    public function retrieveDocumentsByDossierNotInvisible($intDossierId,$boolEstJoint)
    {
      $objRequeteDoctrine = Doctrine_Query::create()
        -> from ('Documents_bpi d')
        -> where('d.dossier_bpi_id = ?',$intDossierId)
        -> andWhere('d.est_joint = ?',$boolEstJoint)
        -> andWhere('d.est_invisible = 0');

        return $objRequeteDoctrine ->execute();
    }
}