<?php

/**
 * Documents_mip_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Documents_mip_type extends BaseDocuments_mip_type
{
  public function __toString()
  {
    if($this->getIntitule() != NULL)
    {
      return $this->getIntitule();
    }
    else
    {
      return "";
    }
    
  }

}