<?php

/**
 * Dossier_these_laboratoire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Dossier_these_laboratoire extends BaseDossier_these_laboratoire
{

  /*
   * Retourne l'intitule du laboratoire
   * @author Alexandre WETTA
   */
  public function afficheLaboratoireComplet(){
    return $this->getLaboratoire()->getIntitule();
  }
  
}