<?php

/**
 * Dossier_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Dossier_postdocTable extends Dossier_mrisTable
{

    private $typeDossier = "Dossier_postdoc";

    /**
     * Returns an instance of this class.
     *
     * @return object Dossier_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dossier_postdoc');
    }


    public function getTypeDossier() {
      return $this->typeDossier;
    }
     /**
     *  Fourni des représentants cannoniques pour les années de création (widget Année Filtre)
     * @return DoctrineCollection liste des dossiers représentants canoniques
     *                            des années de création présentes en base
     * Auteur : Actimage, WilliamR
     */
    public function getAnneesDossiers() {
      return parent::getAnneesDossiers();
    }

   /**
   * Cherche les dossiers actifs avec un statut "Validé" de l'année de la commission et de l'année suivante
   * en fonction d'un domaine scientifique
   * @param String $anneeCommission L'année de la commission(format 'Y')
   * @param Integer $domaineScId  L'id du domaine scientifique
   * @return Requete doctrine
   * Auteur : Actimage
   */
  public function retrieveDossierValideByDomaineScientifiqueId($domaineScId,$anneeCommission ){
    return parent::retrieveDossierMRISValideByDomaineScientifiqueId($domaineScId, $anneeCommission, Statut_dossier_postdocTable::VALIDE);
  }
  

   /**
   * Cherche les dossiers actifs avec un statut "Proposition" de l'année de la commission et de l'année suivante
   * en fonction d'un domaine scientifique
   * @param String $anneeCommission L'année de la commission(format 'Y')
   * @param String $dateCommission La date de la commission (format 'Y-m-d')
   * @param Integer $domaineScId  L'id du domaine scientifique
   * @return Requete Doctrine    
   * Auteur : Actimage
   */
  public function retrieveDossierPropositionByDomaineScientifiqueId($domaineScId,$anneeCommission,$dateCommission ){
    return parent::retrieveDossierMRISPropositionByDomaineScientifiqueId($domaineScId, $anneeCommission, $dateCommission, Statut_dossier_ereTable::PROPOSITION);
  }
}