<?php

/**
 * Echec_authentificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Echec_authentificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Echec_authentificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Echec_authentification');
    }

  /**
   * Permet de verifier s'il existe un echec de connection dans les dernier N minutes
   *
   * @param integer $intIdObjet Id de l'echec, vis-à-vis la base de données
   * @param integer $intMinutes Nombre de minutes à rétrospecter
   * @return boolean
   *
   * @author Simeon PETEV
   */
  public function existsEchecLesNDernierMinutes($intIdObjet, $intMinutes)
  {
    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $objQuery = $this->getInstance()->getQueryObject()
                                        ->where('id = ?',$intIdObjet)
                                        ->andWhere('TIMESTAMPDIFF(MINUTE,updated_at,sysdate()) < ? ',$intMinutes)
    ;

    $boolExists = ($objQuery->count() > 0);

    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $boolExists;
  }
}