<?php

/**
 * EcheanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EcheanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EcheanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Echeance');
    }
}