<?php

/**
 * Encadrant_ereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Encadrant_ereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Encadrant_ereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Encadrant_ere');
    }
    
  /**
   * Construit un query qui recupere les encadrant liés à un dossier
   *
   * @param string $strDossierTheseId Id du dossier vis-à-vis la base de données
   * @return object Doctrine_Query
   *
   * @author Simeon PETEV
   */
  public function buildQueryAvecDossierId($strDossierEreId)
  {
    if (sfContext::hasInstance())
      sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $objQuery = $this->getQueryObject()
                      ->where('dossier_ere_id = ?',$strDossierEreId);

    if (sfContext::hasInstance())
      sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");


    return $objQuery;
  }
}