<?php

/**
 * Encadrant_theseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Encadrant_theseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Encadrant_theseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Encadrant_these');
    }

  /**
   * Construit un query qui recupere les encadrant liés à un dossier
   *
   * @param string $strDossierTheseId Id du dossier vis-à-vis la base de données
   * @return object Doctrine_Query
   *
   * @author Simeon PETEV
   */
  public function buildQueryAvecDossierId($strDossierTheseId)
  {
    if (sfContext::hasInstance())
      sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $objQuery = $this->getQueryObject()
                      ->where('dossier_these_id = ?',$strDossierTheseId);

    if (sfContext::hasInstance())
      sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $objQuery;
  }
}