<?php

/**
 * Ftp_dossier_recupereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ftp_dossier_recupereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ftp_dossier_recupereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ftp_dossier_recupere');
    }
}