<?php

/**
 * Laboratoire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Laboratoire extends BaseLaboratoire
{

  public function  __toString() {
    return $this->getIntitule();
  }

  /**
   *  Verifie si les organismes/services auquels le laboratoire est attaché sont actif
   * @return bool true si toute la hiérarchie est active, false sinon
   */
  public function getEstActifRecursif(){
    if (isset($this['Organisme'])){
      return ($this->getEstActif() || $this['Organisme']->getEstActif());
    } else {
      return ($this->getEstActif() || $this['Service']->getEstActifRecursif());
    }

  }

  /**
   * Permet de décider si l'objet a un service ou pas
   * @return boolean true si l'objet a un service
   *                 false sinon
   * @author Gabor JAGER
   */
  public function hasService()
  {
    if ($this->service_id != null)
    {
      return true;
    }

    return false;
  }

  /**
   * Permet de décider si l'objet a un organisme ou pas
   * @return boolean true si l'objet a un organisme
   *                 false sinon
   * @author Gabor JAGER
   */
  public function hasOrganisme()
  {
    if ($this->organisme_id != null)
    {
      return true;
    }

    return false;
  }

}