<?php

/**
 * Mail_statutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mail_statutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mail_statutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mail_statut');
    }
}