<?php

/**
 * MetierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetierTable extends Doctrine_Table
{
  /**
   * Valeurs des intitulés
   */
  const BPI               = "BPI";
  const BPI_ID            = "1";
  const MIP               = "MIP";
  const MIP_ID            = "2";
  const MRIS              = "MRIS";
  const MRIS_ID           = "3";
  const ADMINISTRATEUR    = "Administrateur";
  const ADMINISTRATEUR_ID = "4";
  
  /**
   * Returns an instance of this class.
   *
   * @return object MetierTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Metier');
  }

  public function getMetiersParUtilisateur($intUtilisateurId) {
    $requete = Doctrine_Query::create()
                  ->from('Metier m')
                  ->innerJoin('m.Profil p ON m.id = p.metier_id')

                  ->innerJoin('p.Utilisateur_profil up ON p.id = up.profil_id')

                  ->where('up.utilisateur_id = ?', $intUtilisateurId);

    return $requete->execute();
  }

  /**
   * Permet de recuperer tous les métiers sans administrateur
   * @param integer $intUtilisateurId
   * @return Doctrine_Collection
   * @author Gabor JAGER
   */
  public function getMetiersSansAdministrateur()
  {
    return $this->getMetiersSansAdministrateurQuery()->execute();
  }

  /**
   * Raquet de recuperation tous les métiers sans administrateur (avec ou sans filtre)
   * @param integer[] $arrMetierFiltre
   * @return Doctrine_Query
   * @author Gabor JAGER
   */
  public function getMetiersSansAdministrateurQuery($arrMetierFiltre=null)
  {
    $objQuery = $this->createQuery()
                     ->where('est_administrateur = 0')
                     ->orderBy("intitule");

    if ($arrMetierFiltre != null)
    {
      $objQuery->andWhereIn("intitule", $arrMetierFiltre);
    }

    return $objQuery;
  }
}
