<?php

/**
 * Mode_transmission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Mode_transmission extends BaseMode_transmission
{
    /**
   * Surcharge la methode par defaut pour retourner l'intidulé
   *
   * @return String
   *
   * @author Actimage
   */
  public function  __toString()
  {
    return $this->getIntitule();
  }

}