<?php

/**
 * Modele_lettreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Modele_lettreTable extends Doctrine_Table
{
  const MIP_LETTRE_PROJET_UN_INNOVATEUR         = "mip_lettre_projet_un_innovateur";
  const MIP_LETTRE_PROJET_PLUSIEURS_INNOVATEURS = "mip_lettre_projet_plusieurs_innovateurs";

  const MIP_LETTRE_SOUTIEN_UN_INNOVATEUR          = "mip_lettre_soutien_un_innovateur";
  const MIP_LETTRE_SOUTIEN_PLUSIEURS_INNOVATEURS  = "mip_lettre_soutien_plusieurs_innovateurs";

  const MIP_LETTRE_CLOTURE_UN_INNOVATEUR_EM       = "mip_lettre_cloture_un_innovateur_em";
  const MIP_LETTRE_CLOTURE_UN_INNOVATEUR_MINDEF   = "mip_lettre_cloture_un_innovateur_mindef";
  const MIP_LETTRE_CLOTURE_PLUSIEURS_INNOVATEURS_MINDEF   = "mip_lettre_cloture_plusieurs_innovateurs_mindef";
  const MIP_LETTRE_ACCUSE_RECEPTION_VISITE        = "mip_lettre_accuse_reception_visite";

  const VARIABLES_MIP_LETTRE_PROJET_UN_INNOVATEUR = "date, dossier_numero, dossier_titre, pilote, pilote_tel, pilote_fax, pilote_mail, dossier_incr, dossier_reference, innovateur, dossier_description, date_etat_avancement, date_compte_rendu, copie_unite_innov, libelle_destinataire, libelle_correspondant";
  const VARIABLES_MIP_LETTRE_PROJET_PLUSIEURS_INNOVATEURS = "date, dossier_numero, dossier_titre, pilote, pilote_tel, pilote_fax, pilote_mail, dossier_incr, dossier_reference, innovateurs, dossier_description, date_etat_avancement, date_compte_rendu, copie_unite_innov, libelle_destinataire, libelle_correspondant";

  const VARIABLES_MIP_LETTRE_SOUTIEN_UN_INNOVATEUR     = "date, dossier_numero, dossier_titre, innovateur, copie_unite_innov, lui_leur, innovateur_innovateurs, son_leur, ea_date, cr_date, description_dossier, financement_total, repartition_financement, entite_financement, libelle_destinataire";
  const VARIABLES_LETTRE_SOUTIEN_PLUSIEURS_INNOVATEURS = "date, dossier_numero, dossier_titre, innovateur, copie_unite_innov, lui_leur, innovateur_innovateurs, son_leur, ea_date, cr_date, description_dossier, financement_total, repartition_financement, entite_financement, libelle_destinataire";

  const VARIABLES_MIP_LETTRE_CLOTURE_UN_INNOVATEUR_EM = "date, dossier_incr, dossier_numero, dossier_titre, innovateur, reference_lettre_soutien, reference_reception_cr, video, reference_video, copie_unite_innov, pilote, pilote_tel, pilote_fax, pilote_mail";
  const VARIABLES_MIP_LETTRE_CLOTURE_UN_INNOVATEUR_MINDEF = "date, dossier_incr, dossier_numero, dossier_titre, cloture, innovateur, reference_lettre_soutien, reference_reception_cr, video, pilote, pilote_tel, pilote_fax, pilote_mail, piece_jointe_cr, reference_video, dossier_cloture, copie_unite_innov, contact_se, libelle_destinataire";
  const VARIABLES_MIP_LETTRE_CLOTURE_PLUSIEURS_INNOVATEURS_MINDEF = "date, dossier_incr, dossier_numero, dossier_titre, cloture, innovateurs, reference_lettre_soutien, reference_reception_cr, video, pilote, pilote_tel, pilote_fax, pilote_mail, piece_jointe_cr, reference_video, dossier_cloture, copie_unite_innov,contact_se, libelle_destinataire";
  const VARIABLES_MIP_LETTRE_ACCUSE_RECEPTION_VISITE = "date, dossier_incr, pilote, pilote_tel, pilote_fax, pilote_mail, innovateur, dossier_numero, dossier_titre, copie_unite_innov, date_rdv, unite, ville, nom_organisme";
  
  /**
   * Returns an instance of this class.
   *
   * @return Modele_lettreTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Modele_lettre');
  }


  /**
   * Permet de récuperer un modèle à partir de son clé
   * @param string $strCle
   * @return Modele_lettre
   * @author GAbor JAGER
   */
  public function getModeleLettreParCle($strCle)
  {
    return $this->findOneByCle($strCle);
  }

  /**
   * Permet de décider si le fichier modèle est bien uploadé ou pas
   * @return boolean true si le fichier modèle est disponible
   *                 false sinon
   * @author GAbor JAGER
   */
  public function estModeleLettreDisponible($strCle)
  {
    $objModeleLettre = $this->getModeleLettreParCle($strCle);

    if ($objModeleLettre == null)
    {
      return false;
    }

    return $objModeleLettre->estDisponible();
  }
}