<?php

/**
 * Niveau_protectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Niveau_protectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Niveau_protectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Niveau_protection');
    }
}