<?php

/**
 * Organisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Organisme extends BaseOrganisme
{

 public function  __toString()
  {
    if ($this->getIntitule() != null){
     return $this->getIntitule();}
    else
      return "";
  }

  public function getEstActifRecursif(){
    return $this->getEstActif();
  }

  /**
   *  Cherche la part de cofinance d'un organisme pour un dossier these donnée et pour une session donnée (double liste)
   * @param Integer   $intDossierId     identifiant du dossier de these
   * @param String    $strSessionToken  transaction token correspondant à la manipulation de double liste en cours
   * @return Integer  valeure de la part de cofinancement (%age)
   */
  public function getPartCofinanceSession($intDossierId, $strSessionToken){
    $objSessionCofinancement = Session_cofinance_theseTable::getInstance()->getSessionByOrganismeIdAndToken($this->getId(),$strSessionToken);
    $objPartCofinance = null;

    $arrPartsCofinances = $this['Cofinance_these'];
    foreach ($arrPartsCofinances as $objPart){
      if ($objPart->getDossier_theseId() == $intDossierId){
        $objPartCofinance = $objPart;
      }
    }
    if (isset($objSessionCofinancement[0])){
      return $objSessionCofinancement[0]->getPartCofinance();
    }
    if ($objPartCofinance){
      return $objPartCofinance->getPartCofinance();
    }
    return 0;
  }
}