<?php

/**
 * PaiementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaiementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaiementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paiement');
    }

  /**
   * Creer un query permettant de recupere les paiements par ordre decendant
   * de la date
   *
   * @param $intDossierId Id du dossier
   * @return Doctrine_Query
   *
   * @author Simeon PETEV
   */
  public function buildQueryPaiementsOrdreDescDate($intDossierId=0)
  {
    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $objQuery = $this->getInstance()->getQueryObject()
                                        ->where('dossier_mip_id = ?',$intDossierId)
                                        ->orderBy('date_paiement DESC')
    ;

    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $objQuery;
  }

  /**
   * Recupere les paiements par ordre decendant de la date
   *
   * @return Doctrine_Collection
   *
   * @author Simeon PETEV
   */
  public function retrevePaiementsOrdreDescDate($intDossierId=0)
  {
    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $arrFinancements = $this->buildQueryPaiementsOrdreDescDate($intDossierId)->execute();

    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $arrFinancements;
  }
}