<?php

/**
 * Prix_dossier_mipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Prix_dossier_mipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return Prix_dossier_mipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Prix_dossier_mip');
    }

    public function retrievePrixByDossierId($strDossierId)
    {
      $objResultat = new Doctrine_Collection('Prix_dossier_mip');
      $objDossier = Dossier_mipTable::getInstance()->findOneById($strDossierId);

      foreach ( PrixTable::getInstance()->findAll() as $prix)
      {
        $objPrixDossier = $this->createQuery('p')->where('p.dossier_mip_id = ?',$strDossierId)
                                                 ->andWhere('p.prix_id = ?',$prix->getId())
                                                 ->execute();
        if ($objPrixDossier->count() == 1){
          $objResultat->add($objPrixDossier[0]);
        } else {
          $objNouveauPrixDossier = new Prix_dossier_mip();
          $objNouveauPrixDossier->setDossierMipId($objDossier->getId());
          $objNouveauPrixDossier->setPrix($prix);
          $objNouveauPrixDossier->setAnnee($objDossier->getAnnee());
          $objResultat->add($objNouveauPrixDossier);
        }
      }

      return $objResultat;
    }
}