<?php

/**
 * Remarque_mrisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Remarque_mrisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Remarque_mrisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Remarque_mris');
    }
}