<?php

/**
 * Role_ereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Role_ereTable extends Doctrine_Table
{

  const DIRECTEUR_ERE = "1";

    /**
     * Returns an instance of this class.
     *
     * @return object Role_ereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Role_ere');
    }
}