<?php

/**
 * Role_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Role_postdocTable extends Doctrine_Table
{

  const DIRECTEUR_POSTDOC = "1";
  
    /**
     * Returns an instance of this class.
     *
     * @return object Role_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Role_postdoc');
    }
}