<?php

/**
 * Session_encadrants_dossier_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Session_encadrants_dossier_postdocTable extends Session_supportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Session_encadrants_dossier_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Session_encadrants_dossier_postdoc');
    }
}