<?php

/**
 * Session_dossier_postdoc_laboratoireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Session_dossier_postdoc_laboratoireTable extends Session_supportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Session_dossier_postdoc_laboratoireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Session_dossier_postdoc_laboratoire');
    }

  /**
   * Construit un query pour recupere les laboratoires assossiées à un dossier dans
   * la session
   *
   * @param String $strToken Le token de transaction
   * @param integer $intIdDossierPostdoc Le id du dossier de thèse vis-à-vis la base de données
   * @return Doctrine_Query
   *
   * @author Simeon PETEV
   */
  public function buildQueryLaboratoiresAssossies($strToken,$intIdDossierPostdoc)
  {
    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $objQuery = $this->getInstance()->getQueryObject()
                                        ->where('transaction_token = ?',$strToken)
                                        ->andWhere('dossier_postdoc_id = ?',$intIdDossierPostdoc)
    ;

    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $objQuery;
  }


  /**
   * Recupere les ids des laboratoires assossiées à un dossier de thèse
   *
   * @param String $strToken Le token de transaction
   * @param integer $intIdDossierPostdoc Le id du dossier de thèse vis-à-vis la base de données
   * @return array Un array de ids
   *
   * @author Simeon PETEV
   */
  public function getIdsLaboratoiresAssocies($strToken,$intIdDossierPostdoc)
  {
    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ DEBUT; ");

    $arrResultatsIds = array();

    $arrSessionRes = $this->buildQueryLaboratoiresAssossies($strToken, $intIdDossierPostdoc)->execute();

    foreach ($arrSessionRes as $objSessionRes)
    {
      $arrResultatsIds[] = $objSessionRes->getLaboratoireId();
    }

    if (sfContext::hasInstance())
        sfContext::getInstance()->getLogger()->debug("{".__CLASS__."} [".__FUNCTION__."] /Ligne: ".__LINE__."/ FIN; ");

    return $arrResultatsIds;
  }
}