<?php

/**
 * Session_liaison_dossiers_bpi_mipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Session_liaison_dossiers_bpi_mipTable extends Session_supportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Session_liaison_dossiers_bpi_mipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Session_liaison_dossiers_bpi_mip');
    }

    public function getSessionByDossierMIPIdAndToken($intIdDossier,$strTransactionToken){
      $requete = $this->createQuery('s')->where('s.dossier_mip_id = ?', $intIdDossier)
                      ->andWhere('s.transaction_token = ?', $strTransactionToken);

      $collection = $requete->execute();
      return $collection;
    }
}