<?php

/**
 * SignataireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SignataireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SignataireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Signataire');
    }
}