<?php

/**
 * SoutienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SoutienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SoutienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Soutien');
    }
}