<?php

/**
 * Statut_projet_mip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Statut_projet_mip extends BaseStatut_projet_mip
{
  public function  __toString() {
    return $this->getIntitule();
  }
}