<?php

/**
 * Statut_dossier_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Statut_dossier_postdocTable extends Doctrine_Table
{
  const PROPOSITION = "1";
  const VALIDE = "2" ;
  const REFUSE = "3" ;
  const MIS_EN_ATTENTE = "4" ;
  
    /**
     * Returns an instance of this class.
     *
     * @return object Statut_dossier_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Statut_dossier_postdoc');
    }
}