<?php

/**
 * TacheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TacheTable extends Doctrine_Table
{
  const CREATION_ALERTES_BPI     = "alertes_bpi";
  const CREATION_MAIL_DE_RELANCE = "relances_mip";
  const ENVOI_MAILS              = "mails";
  const GRID_TEST_UNIT           = "test";
  const IMPORTATION_MRIS         = "importation_mris";
  const PURGE_SESSION            = "purgesession";
  const RECUPERATION_DOSSIER_FTP = "recuperation_dossier_ftp";
  const TACHES                   = "taches";
  const TACHE_A_TUER             = "tacheatuer";

  /**
   * Returns an instance of this class.
   *
   * @return TacheTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Tache');
  }

  /**
   * Permet de récuperer un objet tâche à partir de son clé
   * @param string $strCle
   * @return Tache
   * @author GAbor JAGER
   */
  public function getTacheParCle($strCle)
  {
    return $this->findOneByCle($strCle);
  }

  /**
   * Permet de récuperer tous les tâches gerables dans l'application
   * @return array
   * @author GAbor JAGER
   */
  public function getTaches()
  {
    $arrRetour = array();

    $arrRetour[self::CREATION_ALERTES_BPI]     = $this->getTacheParCle(self::CREATION_ALERTES_BPI);
    $arrRetour[self::CREATION_MAIL_DE_RELANCE] = $this->getTacheParCle(self::CREATION_MAIL_DE_RELANCE);
    $arrRetour[self::ENVOI_MAILS]              = $this->getTacheParCle(self::ENVOI_MAILS);
    $arrRetour[self::IMPORTATION_MRIS]         = $this->getTacheParCle(self::IMPORTATION_MRIS);
    $arrRetour[self::PURGE_SESSION]            = $this->getTacheParCle(self::PURGE_SESSION);
    $arrRetour[self::RECUPERATION_DOSSIER_FTP] = $this->getTacheParCle(self::RECUPERATION_DOSSIER_FTP);
//    $arrRetour[self::TACHE_A_TUER]             = $this->getTacheParCle(self::TACHE_A_TUER);

    return $arrRetour;
  }
}