<?php

/**
 * Transfert_clotureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Transfert_clotureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Transfert_clotureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Transfert_cloture');
    }
}