<?php

/**
 * Type_actionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_actionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Type_actionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_action');
    }
}