<?php

/**
 * Type_depot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Type_depot extends BaseType_depot
{

  public function  getIntituleComplet() {

    if($this->getAbreviation() == NULL){
      return $this->getIntitule();
    }  else {
      return  $this->getAbreviation()." - ". $this->getIntitule();
    }

  }

}