<?php

/**
 * Type_suivi_these
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Type_suivi_these extends BaseType_suivi_these
{
  public function  __toString()
  {
    return $this->getIntitule();
  }

}