<?php

/**
 * Type_cursusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_cursusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Type_cursusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_cursus');
    }
}