<?php

/**
 * Type_document_ere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Type_document_ere extends BaseType_document_ere
{
 public function  __toString() {
    return $this->getIntitule();
  }
}