<?php

/**
 * Type_evenement_postdocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_evenement_postdocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Type_evenement_postdocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_evenement_postdoc');
    }
}