<?php

/**
 * Type_suivi_theseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_suivi_theseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Type_suivi_theseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_suivi_these');
    }
}