<?php

/**
 * Type_convention_organisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Type_convention_organisme extends BaseType_convention_organisme {

  /**
   * Permet d'afficher une convention sans le mot "thèse" à l'affichage
   *
   * @return <string>
   */
  public function afficheConventionPourThese() {
    $str = $this->getIntitule();
    $str = str_replace('Thèse - ', '', $str);
    return $str;
  }

}