<?php

/**
 * Type_document_ereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Type_document_ereTable extends Doctrine_Table
{
  const AUTRE = 100;
    /**
     * Returns an instance of this class.
     *
     * @return object Type_document_ereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type_document_ere');
    }
}