<?php

/**
 * Valorisation_interneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Valorisation_interneTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object Valorisation_interneTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Valorisation_interne');
  }

  /**
   * Permet de recuperer tous les valorisations internes d'un dossier
   * @param integer $intDossierId
   * @return Doctrine_Collection
   * @author Gabor JAGER
   */
  public function getValorisationsInternesByDossierId($intDossierId)
  {
    $objRequete = $this->createQuery('vi')
                       ->leftJoin("vi.Valorisation_bpi vb ON vi.valorisation_bpi_id = vb.id")
                       ->where("vb.dossier_bpi_id = ?", $intDossierId);

    return $objRequete->execute();
  }
}
