<?php

/**
 * Versement_dossier_ereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Versement_dossier_ereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Versement_dossier_ereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Versement_dossier_ere');
    }

    public function getVersementByDossierId($intDossierId)
    {
      return $this->createQuery('v')->where('v.dossier_ere_id = ?', $intDossierId)->orderBy('date_versement')->execute();
    }
}