<?php

/**
 * View_recherche
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gridSI
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class View_recherche extends BaseView_recherche
{

  public function getDossier(){
    if ($this->getDossierBpiId() != null){
      return $this->getDossier_bpi();
    }
    if ($this->getDossierMipId() != null){
      return $this->getDossier_mip();
    }
    if ($this->getDossierEreId() != null){
      return $this->getDossier_ere();
    }
    if ($this->getDossierPostdocId() != null){
      return $this->getDossier_postdoc();
    }
    if ($this->getDossierTheseId() != null){
      return $this->getDossier_these();
    }
  }


  /**
   * Permet de recuperer une liste des personnes concernées
   * @return array liste des personnes concernées
   * @author Gabor JAGER
   */
  public function getPersonnesConcernes()
  {
    $arrRetour = array();
    
    // dossier BPI
    if ($this->getDossierBpiId() != null)
    {
      $arrInventeurs = $this->getDossier_bpi()->getInventeurs();

      foreach($arrInventeurs as $objInventeur)
      {
        $arrRetour[] = $objInventeur;
      }
    }

    // dossier MIP
    else if ($this->getDossierMipId() != null)
    {
      $arrInnovateurs = $this->getDossier_mip()->getInnovateurs();

      foreach($arrInnovateurs as $objInnovateur)
      {
        $arrRetour[] = $objInnovateur;
      }
    }

    // dossier ERE
    else if ($this->getDossierEreId() != null)
    {
      $arrRetour[] = $this->getDossier_ere()->getEtudiant();
    }

    // dossier Postdoc
    else if ($this->getDossierPostdocId() != null)
    {
      $arrRetour[] = $this->getDossier_postdoc()->getEtudiant();
    }

    // dossier Thèse
    else if ($this->getDossierTheseId() != null)
    {
      $arrRetour[] = $this->getDossier_these()->getEtudiant();
    }

    return $arrRetour;
  }

}