<?php

/**
 * VilleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return VilleTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Ville');
  }

  /**
   *  Methode retournant la requête doctrine selectionnant les grades d'un département (triés)
   * @param   string $id identifiant du departement
   * @return  DoctrineQuery requête Doctrine à passer au paginateur ou au filtre
   */
  public function getVillesByDepartementId($intDepartementId) {
    return self::getInstance()->createQuery('v')
            ->where('v.departement_id = ?', $intDepartementId)
            ->orderBy('v.nom ASC');
  }

  /**
   * Trie les villes par ordre alphabetique de la requête fournie, ou renvoie l'ensemble des villes triées
   *
   * @param  Requête   $requete   requête construite en amont à trier (par nom)
   * @return DoctrineCollection
   * Auteurs: William Richards
   */
  public function orderVilles($requete = null) {
    if (is_null($requete)) {
      $requete = $this->createQuery();
    }

    $requete->orderBy('nom');

    return $requete;
  }

  /**
   * Construit un query qui permet de recupere les villes actifs, triés en ordre
   * alphabetique de l'intitulé
   * @return Doctrine_Query
   */
  public function buildQueryVilleActifsOrdreAscPourSelectBox($strCodePostal = null)
  {
    $objQuery = Doctrine_Query::create()
                    ->select("v.*")
                    ->from("Ville v")
                    ->addFrom("Departement d")
                    ->where("v.est_actif = 1")
                    ->andWhere("v.departement_id = d.id")
                    ->andWhere("d.est_actif = 1")
                    ->orderBy("nom ASC");

    if ($strCodePostal)
    {
      $strCodePostal .= "%";
      $objQuery->andWhere("v.code_postal LIKE ?", $strCodePostal);
    }
    else
    {
      $objQuery->andWhere("false");
    }

    return $objQuery;
  }


  /**
   * Retrouve les villes en fonction d'une région
   * @param int $regionId Id de la région
   * @author Alexandre WETTA
   * return Doctrine_query 
   */
  public function retrieveVilleParRegion($regionId) {
    
    $queryVille = $this->createQuery('v')->innerJoin('v.Departement d')
                    ->where('d.region_id = ?', $regionId);

    return $queryVille ;
  }

}